### ISSUE TITLE
ValueError: Namespace Wnck not available

### ISSUE THREAD

**Issue by cheap-glitch** [Ulauncher/Ulauncher#1005]
### Environment

Arch Linux + Wayland (Sway)

### Bug description

I have installed `ulauncher-git` and enabled the service as instructed by the package. After rebooting, `systemctl --user status ulauncher` gives the following output:

```
● ulauncher.service - Linux Application Launcher
     Loaded: loaded (/usr/lib/systemd/user/ulauncher.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-03-30 08:36:42 CEST; 3s ago
       Docs: https://ulauncher.io/
   Main PID: 2206 (ulauncher)
      Tasks: 4 (limit: 4545)
     Memory: 25.7M
        CPU: 252ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/ulauncher.service
             └─2206 /bin/python /usr/bin/ulauncher --no-window

mars 30 08:36:42 HAL9000 ulauncher[2206]:     from ulauncher.ui.ResultWidget import ResultWidget  # noqa: F401
mars 30 08:36:42 HAL9000 ulauncher[2206]:   File "/usr/lib/python3.10/site-packages/ulauncher/ui/ResultWidget.py", line 9, in <module>
mars 30 08:36:42 HAL9000 ulauncher[2206]:     from ulauncher.utils.wm import get_scaling_factor
mars 30 08:36:42 HAL9000 ulauncher[2206]:   File "/usr/lib/python3.10/site-packages/ulauncher/utils/wm.py", line 3, in <module>
mars 30 08:36:42 HAL9000 ulauncher[2206]:     gi.require_versions({
mars 30 08:36:42 HAL9000 ulauncher[2206]:   File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 149, in require_versions
mars 30 08:36:42 HAL9000 ulauncher[2206]:     require_version(module_name, module_version)
mars 30 08:36:42 HAL9000 ulauncher[2206]:   File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
mars 30 08:36:42 HAL9000 ulauncher[2206]:     raise ValueError('Namespace %s not available' % namespace)
mars 30 08:36:42 HAL9000 ulauncher[2206]: ValueError: Namespace Wnck not available
```

Running `unlauncher` or `ulauncher-toggle` produces no output and exits with 0.

-----

I have installed the latest version of `xorg-xwayland` (v22.1) and these are my env settings related to Wayland (not that these should affect `systemd`, but you never know):

```
MOZ_ENABLE_WAYLAND=1
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt5ct
WINIT_UNIX_BACKEND=wayland
XDG_CURRENT_DESKTOP=sway
```

### Log output

```shell
Ulauncher version 6.0.0
Extension API version 2.0
GTK+ 3.24.33
Session type: wayland
X11 backend: Yes
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
Should be fixed now in the package. Thank you for reporting :+1:

**Comment by PAI5REECHO** [comment]
Is there a way to fix this while developing locally? I'm trying to write a pull request and this happens when launching:
```command
$ env GDK_BACKEND=wayland ./bin/ulauncher -v
running build_prefs
Detected no changes to Preferences since last build.
Ulauncher version 6.0.0
2022-04-12 01:34:32,988 | INFO | ulauncher: main() | Ulauncher version 6.0.0
Extension API version 2.0
2022-04-12 01:34:32,990 | INFO | ulauncher: main() | Extension API version 2.0
GTK+ 3.24.33
2022-04-12 01:34:32,999 | INFO | ulauncher: main() | GTK+ 3.24.33
Session type: wayland
2022-04-12 01:34:33,000 | INFO | ulauncher: main() | Session type: wayland
X11 backend: No
2022-04-12 01:34:33,002 | INFO | ulauncher: main() | X11 backend: No

(ulauncher:3193113): Gdk-WARNING **: 01:34:33.090: Failed to load cursor theme elementary
Uncaught exception
Traceback (most recent call last):
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/main.py", line 37, in setup
    from ulauncher.ui.windows.UlauncherWindow import UlauncherWindow
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/ui/windows/UlauncherWindow.py", line 16, in <module>
    from ulauncher.ui.ResultWidget import ResultWidget  # noqa: F401
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/ui/ResultWidget.py", line 9, in <module>
    from ulauncher.utils.wm import get_scaling_factor
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/utils/wm.py", line 3, in <module>
    gi.require_versions({
  File "/nix/store/qka6ky17p6l87l73863mzds284mvxi5d-python3-3.8.13-env/lib/python3.8/site-packages/gi/__init__.py", line 149, in require_versions
    require_version(module_name, module_version)
  File "/nix/store/qka6ky17p6l87l73863mzds284mvxi5d-python3-3.8.13-env/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available
2022-04-12 01:34:33,099 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/main.py", line 37, in setup
    from ulauncher.ui.windows.UlauncherWindow import UlauncherWindow
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/ui/windows/UlauncherWindow.py", line 16, in <module>
    from ulauncher.ui.ResultWidget import ResultWidget  # noqa: F401
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/ui/ResultWidget.py", line 9, in <module>
    from ulauncher.utils.wm import get_scaling_factor
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/utils/wm.py", line 3, in <module>
    gi.require_versions({
  File "/nix/store/qka6ky17p6l87l73863mzds284mvxi5d-python3-3.8.13-env/lib/python3.8/site-packages/gi/__init__.py", line 149, in require_versions
    require_version(module_name, module_version)
  File "/nix/store/qka6ky17p6l87l73863mzds284mvxi5d-python3-3.8.13-env/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available
Uncaught exception
Traceback (most recent call last):
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/main.py", line 42, in do_activate
    self.window.show_window()
AttributeError: 'NoneType' object has no attribute 'show_window'
2022-04-12 01:34:33,125 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/home/me/git/Ulauncher/Ulauncher/ulauncher/main.py", line 42, in do_activate
    self.window.show_window()
AttributeError: 'NoneType' object has no attribute 'show_window'
```
