### ISSUE TITLE
can not add extension，github reject connect, can I install extensions manually？

### ISSUE THREAD

**Issue by mdmbct** [Ulauncher/Ulauncher#1023]
### Environment

Manjaro Gnome, Linux Kernel 5.15.32-1-MANJARO

### Bug description

can not add extension，github reject connect.
Can I install extensions manually？

### Log output

```shell
2022-05-01 00:19:48,330 | INFO | ulauncher: main() | Ulauncher version 5.14.4
2022-05-01 00:19:48,330 | INFO | ulauncher: main() | Extension API version 2.0.0
2022-05-01 00:19:48,330 | INFO | ulauncher: main() | GTK+ 3.24.33
2022-05-01 00:19:48,330 | INFO | ulauncher: main() | Is Wayland: False
2022-05-01 00:19:48,331 | INFO | ulauncher: main() | Wayland compatibility: off
2022-05-01 00:19:48,357 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-05-01 00:19:48,360 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2022-05-01 00:19:48,361 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-05-01 00:19:48,361 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-05-01 00:19:48,361 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-05-01 00:19:48,362 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-05-01 00:19:48,362 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-05-01 00:19:48,362 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2022-05-01 00:19:48,362 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-05-01 00:19:48,362 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2022-05-01 00:19:48,364 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-05-01 00:19:48,364 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-05-01 00:19:48,372 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-05-01 00:19:48,374 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2022-05-01 00:19:48,375 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2022-05-01 00:19:48,391 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2022-05-01 00:19:48,397 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 91 apps in cache
2022-05-01 00:19:48,400 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/evolution-calendar.desktop": constructor returned NULL
2022-05-01 00:19:48,412 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.kded5.desktop": constructor returned NULL
2022-05-01 00:19:48,412 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/kcm_trash.desktop": constructor returned NULL
2022-05-01 00:19:48,421 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 91 apps in the system
2022-05-01 00:19:48,421 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.05 seconds
2022-05-01 00:19:48,426 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2022-05-01 00:19:50,015 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-05-01 00:19:50,016 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-05-01 00:19:50,016 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-05-01 00:19:53,562 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2022-05-01 00:19:53,588 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2022-05-01 00:19:53,588 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2022-05-01 00:19:53,652 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2022-05-01 00:19:53,652 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2022-05-01 00:19:53,656 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2022-05-01 00:19:53,657 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2022-05-01 00:19:54,095 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2022-05-01 00:19:55,900 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_set_theme_name() | Set theme-name to dark
2022-05-01 00:19:58,000 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_close() | Close preferences
2022-05-01 00:19:59,934 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-05-01 00:19:59,935 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-05-01 00:19:59,936 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-05-01 00:20:01,598 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-05-01 00:20:01,598 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-05-01 00:20:01,598 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-05-01 00:20:02,352 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | show existing preferences_dialog
2022-05-01 00:20:02,475 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2022-05-01 00:20:22,402 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_shortcut_get_all() | Handling /shortcut/get-all
2022-05-01 00:20:24,754 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_get_all() | Handling /extension/get-all
2022-05-01 00:20:31,124 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_open_url() | Open Web URL https://ext.ulauncher.io
2022-05-01 00:22:06,110 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://github.com/Eckhoff42/Ulauncher-Bluetooth-quick-connect
2022-05-01 00:22:06,152 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. URLError: <urlopen error [Errno 111] 拒绝连接>
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 220, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.10/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 463, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
    for ver in self.read_versions():
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 110, in read_versions
    versions = self._read_json('master', 'versions.json')
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 101, in _read_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] 拒绝连接>
2022-05-01 00:24:15,671 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://github.com/Eckhoff42/Ulauncher-Bluetooth-quick-connect
2022-05-01 00:24:15,691 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. URLError: <urlopen error [Errno 111] 拒绝连接>
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 220, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.10/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 463, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
    for ver in self.read_versions():
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 110, in read_versions
    versions = self._read_json('master', 'versions.json')
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 101, in _read_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] 拒绝连接>
2022-05-01 00:24:22,337 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_get_all() | Handling /extension/get-all
2022-05-01 00:26:57,382 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://github.com/Eckhoff42/Ulauncher-Bluetooth-quick-connect
2022-05-01 00:26:57,413 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. URLError: <urlopen error [Errno 111] 拒绝连接>
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 220, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.10/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 463, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
    for ver in self.read_versions():
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 110, in read_versions
    versions = self._read_json('master', 'versions.json')
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 101, in _read_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] 拒绝连接>
2022-05-01 00:27:03,004 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_open_url() | Open Web URL https://github.com/Ulauncher/Ulauncher/issues
2022-05-01 00:44:29,750 | INFO | ulauncher.search.apps.app_watcher: _add_file_sync() | New app was added "Strace" (/home/jack/.local/share/applications/Strace.desktop)
2022-05-01 00:44:41,029 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_get_all() | Handling /extension/get-all
2022-05-01 00:49:14,006 | INFO | ulauncher.search.apps.app_watcher: _add_file_sync() | New app was added "Strace" (/home/jack/.local/share/applications/Strace.desktop)
2022-05-01 00:49:30,019 | INFO | ulauncher.search.apps.app_watcher: _add_file_sync() | New app was added "Stracer" (/home/jack/.local/share/applications/Strace.desktop)
2022-05-01 00:49:50,225 | INFO | ulauncher.search.apps.app_watcher: _remove_file() | App was removed (/home/jack/.local/share/applications/Strace.desktop)
2022-05-01 00:49:56,039 | INFO | ulauncher.search.apps.app_watcher: _add_file_sync() | New app was added "Stracer" (/home/jack/.local/share/applications/Stracer.desktop)
2022-05-01 00:51:13,595 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-05-01 00:51:13,595 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-05-01 00:51:13,596 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-05-01 01:05:41,833 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://github.com/Rapha149/ulauncher-deepl/
2022-05-01 01:05:41,872 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. URLError: <urlopen error [Errno 111] 拒绝连接>
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 220, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.10/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 463, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
    for ver in self.read_versions():
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 110, in read_versions
    versions = self._read_json('master', 'versions.json')
  File "/usr/lib/python3.10/site-packages/ulauncher/api/server/GithubExtension.py", line 101, in _read_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] 拒绝连接>
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
Yeah. You just have to put them in ~/.local/share/ulauncher/extensions/

See: https://github.com/Ulauncher/Ulauncher/issues/1018#issuecomment-1108600606

**Comment by mdmbct** [comment]
Thank you！！！It would be nice if the [extensions page](https://ext.ulauncher.io/) can supported search ext！😍
