### ISSUE TITLE
Ulauncher Bug 

### ISSUE THREAD

**Issue by devk232** [Ulauncher/Ulauncher#1066]
### Environment

 Ubuntu 22.04 LTS

### Bug description

A dialog box with the following message appears as soon as I open Ulauncher - An unexpected error has occurred.
Here are the details.

Message: Caught an error while switching "autostart": Unexpected exception: [Errno 30] Read-only file system: '/home/dev/.config/autostart/ulauncher.desktop'
Error Name: UnexpectedError
Type: PrefsApiError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/utils/AutostartPreference.py", line 71, in switch
    autostart_info.write()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/desktop/DesktopParser.py", line 45, in write
    with open(self._filename, 'w') as f:
OSError: [Errno 30] Read-only file system: '/home/dev/.config/autostart/ulauncher.desktop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 297, in prefs_set_autostart
    self.autostart_pref.switch(is_on)
  File "/usr/lib/python3/dist-packages/ulauncher/utils/AutostartPreference.py", line 73, in switch
    raise SwitchError('Unexpected exception: %s' % e) from e
ulauncher.utils.AutostartPreference.SwitchError: Unexpected exception: [Errno 30] Read-only file system: '/home/dev/.config/autostart/ulauncher.desktop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 220, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 299, in prefs_set_autostart
    raise PrefsApiError('Caught an error while switching "autostart": %s' % e) from e
ulauncher.ui.windows.PreferencesUlauncherDialog.PrefsApiError: Caught an error while switching "autostart": Unexpected exception: [Errno 30] Read-only file system: '/home/dev/.config/autostart/ulauncher.desktop'

```

### Log output

```shell
DBus name already taken. Ulauncher is probably backgrounded. Did you mean `ulauncher-toggle`?
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
It says the problem in the error: "Read-only file system: '/home/dev/.config/autostart/ulauncher.desktop'"

It doesn't do this when the app opens. It does it when you change the autostart settings. Maybe it could handle it gracefully, but we already fixed this in v6.
