### ISSUE TITLE
Cannot start some applications from ulauncher git version 6

### ISSUE THREAD

**Issue by cycomanic** [Ulauncher/Ulauncher#1072]
### Environment

Arch, sway

### Bug description

If I use the git version of ulauncher (v6 branch from ulauncher-git aur) some applications cannot be started. They show up in the search and I can select them, however pressing return does nothing (the searched result is still there). The same applications worked fine in ulauncher 5.14. 

Two examples:

1. KDE system settings
2. Kmail
3. poweroff, reboot from the system management direct https://github.com/episode6/ulauncher-system-management-direct extension 

There were more, but I did not note them down at the time.

### Log output

```shell
Using GDK_BACKEND=wayland

(ulauncher:15684): Wnck-WARNING **: 16:52:24.084: libwnck is designed to work in X11 only, no valid display found
2022-06-21 16:52:24,097 ℹ️  INFO Ulauncher version 6.0.0 main.main:45
2022-06-21 16:52:24,097 ℹ️  INFO Extension API version 2.0 main.main:46
2022-06-21 16:52:24,097 ℹ️  INFO GTK+ 3.24.34 main.main:47
2022-06-21 16:52:24,097 ℹ️  INFO PyGobject+ 3.42.1 main.main:48
2022-06-21 16:52:24,097 ℹ️  INFO Desktop: sway (WAYLAND) on EndeavourOS main.main:50
2022-06-21 16:52:24,097 ℹ️  INFO X11 backend: No main.main:53

using X11 backend:
2022-06-21 16:57:43,913 ℹ️  INFO Ulauncher version 6.0.0 main.main:45
2022-06-21 16:57:43,913 ℹ️  INFO Extension API version 2.0 main.main:46
2022-06-21 16:57:43,913 ℹ️  INFO GTK+ 3.24.34 main.main:47
2022-06-21 16:57:43,913 ℹ️  INFO PyGobject+ 3.42.1 main.main:48
2022-06-21 16:57:43,913 ℹ️  INFO Desktop: sway (WAYLAND) on EndeavourOS main.main:50
2022-06-21 16:57:43,913 ℹ️  INFO X11 backend: Yes main.main:53
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
https://github.com/episode6/ulauncher-system-management-direct doesn't work because it relies on a hack (found by me incidentally) to do something Ulauncher wasn't intended to handle. I've been considering how/if to provide this in another way for this branch, but it's really only two extensions that are using the hack.

This is not really the log output. It's just the version info from it. It would help to get the output hen you're trying to launch an app.

**Comment by cycomanic** [comment]
Ah sorry, I was uninstalling and reinstalling and somehow forgot to stop the systemd service. Here's the relevant part of the log when starting KDE System Settings:

```python
2022-06-21 17:24:31,403 ℹ️  DEBUG render 24 results UlauncherWindow.show_results:297
2022-06-21 17:24:31,501 ℹ️  DEBUG render 14 results UlauncherWindow.show_results:297
2022-06-21 17:24:31,660 ℹ️  DEBUG render 16 results UlauncherWindow.show_results:297
2022-06-21 17:24:32,104 ⚠️  ERROR Uncaught exception main.except_hook:75
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 123, in on_input_key_press
    self.enter_result()
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 247, in enter_result
    if self.results_nav.enter(self._get_user_query(), index, alt=alt):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/ItemNavigation.py", line 67, in enter
    action = result.on_enter(query) if not alt else result.on_alt_enter(query)
  File "/usr/lib/python3.10/site-packages/ulauncher/modes/apps/AppResult.py", line 67, in on_enter
    return launch_app(self._app_id)
  File "/usr/lib/python3.10/site-packages/ulauncher/modes/apps/launch_app.py", line 21, in launch_app
    for win in get_windows_stacked():
  File "/usr/lib/python3.10/site-packages/ulauncher/utils/wm.py", line 44, in get_windows_stacked
    wnck_screen.force_update()
AttributeError: 'NoneType' object has no attribute 'force_update'
```

And now it only happens with `GDK_BACKEND=wayland`, seems like it is trying to somehow open a window instead of opening the app?

**Comment by friday** [comment]
Yeah. Just the condition that needed fixing :+1: Thanks for finding it :) It's already merged.

I'll create a new issue for the other issue.

**Comment by friday** [comment]
As of #1097 getting merged into v6 (just now) extensions behavior like system manager is now supported directly. Documentation is still lacking, but it's implemented in https://github.com/friday/ulauncher-gnome-settings (v3 branch). So if it's important to you you can fork the extension or mine and work it out from there.
