### ISSUE TITLE
Handle starting v6 while Ulauncher v5 is still running

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#1093]
### Description

If you upgrade to Ulauncher v6 (once released), and try to start it while v5 is running, then you get this error or something similar:
```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/service.py", line 662, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3.10/site-packages/dbus/service.py", line 252, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: DescribeAll is not a valid method of interface org.gtk.Actions
```

Crashing here is good imo, but this message is very unhelpful.

This is from the old dependency v5 used. The dbus package doesn't exist on my system as of running the code, but it's loaded in memory in Ulauncher v5's runtime. This error also can't be caught (`app.run()` in main.py doesn't fail, the except_hook doesn't catch anything and the application "shutdown" or "name-lost" singals aren't triggered).

One way to "fix" it is doing #1092 However, this change alone would be worse than not crashing, because then two different instances of Ulauncher will run simultaneously, which can cause all kinds of issues.

We should probably try to detect if Ulauncher 5 is responding to the dbus calls and crash with a nicer error message (maybe send a desktop notification as well).

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by LinuxOnTheDesktop** [comment]
Might I second this proposal?

I add the following. I have a system that has Ulauncher v. 5. I tried out v.6.0.0-b5. So doing resulted in the following situation. A service called `ulauncher` was failed and, even after resetting it, Ulauncher would not run. So, I returned to version 5. Probably I should file a bug report.

**Comment by friday** [comment]
Thank you @LinuxOnTheDesktop for doing more testing :heart: . I have actually tested this issue recently and since the dbus service app names are now different, I actually had two different versions of Ulauncher running t the same time just fine. This of course is not good though, because they try to use the same settings.

I'm not sure the issue you saw is the fully the same, but if you ran it through systemd, maybe you can see an error with `journalctl --user -u ulauncher --since "1 hours ago"` (changing the time to what you need).

This release may solve your logfile issue, but I am pretty sure we still have one of the critical issues you mentioned earlier (performance related). No one else reported this, so there hasn't been any progress.

**Comment by friday** [comment]
Also, when your systemd service file changes you have to run `systemctl --user daemon-reload && systemctl --user restart ulauncher`, but I assume you know that.

**Comment by friday** [comment]
> Regular users will install a new version over the old one and won't ever run into issues related to running multiple versions.

No, they will. You have to explicitly stop the old service (which you can do since they have different app ids), or restart the OS.

**Comment by gornostal** [comment]
I didn't know v6 would have a different app id. 
If that's needed, so be it.
Then the current task remains actual.
