### ISSUE TITLE
File not found ext_preference  while trying to run from bin 

### ISSUE THREAD

**Issue by UmangX** [Ulauncher/Ulauncher#1096]
### Environment

Ubuntu 22.04 LTS x86_64  , GNOME 42.0 

### Bug description

i read the contributing file and followed the instructions but its giving me the error 

### Log output

```shell
running build_prefs
Detected no changes to Preferences since last build.
2022-07-25 00:53:37,781 ℹ️  INFO Ulauncher version 6.0.0 main.main:46
2022-07-25 00:53:37,781 ℹ️  INFO Extension API version 3.0 main.main:47
2022-07-25 00:53:37,782 ℹ️  INFO GTK+ 3.24.33 main.main:48
2022-07-25 00:53:37,782 ℹ️  INFO PyGobject+ 3.42.0 main.main:49
2022-07-25 00:53:37,782 ℹ️  INFO Desktop: ubuntu:GNOME (X11) on Ubuntu 22.04 LTS main.main:51
2022-07-25 00:53:37,782 ⚠️  ERROR Uncaught exception main.except_hook:76
Traceback (most recent call last):
  File "/home/vergil/dev/Ulauncher/bin/ulauncher", line 29, in <module>
    main()
  File "/home/vergil/dev/Ulauncher/ulauncher/main.py", line 81, in main
    v5_to_v6()
  File "/home/vergil/dev/Ulauncher/ulauncher/utils/migrate.py", line 55, in v5_to_v6
    for file in Path(f"{PATHS.CONFIG}/ext_preferences").iterdir():
  File "/usr/lib/python3.10/pathlib.py", line 1015, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/vergil/.config/ulauncher/ext_preferences'
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thanks for the report :+1:  This is a legit bug (newly introduced). It should either create this path or not fail if it's missing. I'll push a fix soon.
