### ISSUE TITLE
Unable to launcher Ulauncher

### ISSUE THREAD

**Issue by Drezzler** [Ulauncher/Ulauncher#1103]
### Environment

Ubuntu, Gnome with wayland or xorg

### Bug description

After the recent system update that i did 3 days ago, ulauncher wont launch.

I
### Things i have tried:

> - Tried switching from wayland to x11 and back
> - Tried reintalling ulauncher several times

Any help is much appreciated.

### Log output

```shell
2022-08-03 22:11:33,012 | INFO | ulauncher: main() | Ulauncher version 5.14.7
2022-08-03 22:11:33,013 | INFO | ulauncher: main() | Extension API version 2.0.0
2022-08-03 22:11:33,013 | INFO | ulauncher: main() | GTK+ 3.24.33
2022-08-03 22:11:33,013 | INFO | ulauncher: main() | Is Wayland: False
2022-08-03 22:11:33,013 | INFO | ulauncher: main() | Wayland compatibility: off
2022-08-03 22:11:33,030 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-08-03 22:11:33,032 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2022-08-03 22:11:33,032 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-08-03 22:11:33,032 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-08-03 22:11:33,033 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-08-03 22:11:33,033 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-08-03 22:11:33,033 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-08-03 22:11:33,033 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2022-08-03 22:11:33,033 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-08-03 22:11:33,033 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2022-08-03 22:11:33,034 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-08-03 22:11:33,035 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1200
2022-08-03 22:11:33,046 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-08-03 22:11:33,048 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2022-08-03 22:11:33,049 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2022-08-03 22:11:33,054 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.kded5.desktop": constructor returned NULL
2022-08-03 22:11:33,059 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 136, in main
    window = UlauncherWindow.get_instance()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 56, in get_instance
    return cls()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 66, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 114, in finish_initializing
    ExtensionRunner.get_instance().run_all()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionRunner.py", line 53, in run_all
    for id, _ in find_extensions(self.extensions_dir):
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/extension_finder.py", line 22, in find_extensions
    manifest = json.loads(Path(ext_path, 'manifest.json').read_text('utf-8'))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 25 column 7 (char 616)
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
You have an extension with a manifest.json that's not a valid json file, just like the error message says. It doesn't say which one but it's line 25. We should handle that so it doesn't crash here, but you can also check your extensions in `~/.local/share/ulauncher/extensions/`.

**Comment by Drezzler** [comment]
Yup, that did it.

Thank you so much.
