### ISSUE TITLE
Add webkit2gtk as dependency required in arch repository

### ISSUE THREAD

**Issue by argonarch** [Ulauncher/Ulauncher#1105]
### Environment

Arch linux, kde plasma

### Bug description

Error:
Traceback (most recent call last):
File "/usr/bin/ulauncher", line 27, in
from ulauncher.main import main
File "/usr/lib/python3.10/site-packages/ulauncher/main.py", line 25, in
from ulauncher.ui.windows.UlauncherWindow import UlauncherWindow
File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 41, in
from ulauncher.ui.windows.PreferencesUlauncherDialog import PreferencesUlauncherDialog
File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 14, in
gi.require_version('WebKit2', '4.0')
File "/usr/lib/python3.10/site-packages/gi/init.py", line 129, in require_version
raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace WebKit2 not available for version 4.0

Solution: install webkit2gtk

sudo pacman -S webkit2gtk

### Log output

```shell
Ulauncher version 5.14.7
Extension API version 2.0.0
GTK+ 3.24.34
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thanks. Should be fixed now. We always had the webkit2gtk dependency, but forgot to revert it back to the old version in that release.
