### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by Zhong-Zach** [Ulauncher/Ulauncher#1117]
### Environment

KUbuntu 22.04(KDE Plasma Desktop)

### Bug description

I installed ULauncher just now.Then I tried to install some extensions.But it didn't work and showed a error to me.
Note:These extensions all from official ULauncher extensions store.And I'm in China now.

### Log output

```shell
Message: <urlopen error [Errno 111] Connection refused>
Error Name: UnhandledError
Type: URLError

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 220, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 463, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
    for ver in self.read_versions():
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 116, in read_versions
    versions = self._read_json('master', 'versions.json')
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 107, in _read_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

```
```


### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
See #679. It's fixed in the v6 (next major release) branch.

**Comment by friday** [comment]
In the meanwhile if you're on v5, this might help: https://github.com/Ulauncher/Ulauncher/issues/1071#issuecomment-1175921028
