### ISSUE TITLE
Cannot start ulauncher because of unknown key "css_file_gtk_3.20+"

### ISSUE THREAD

**Issue by janemba** [Ulauncher/Ulauncher#1123]
### Environment

GNU/Linux slackware / sway / wayland

### Bug description

- I start `ulauncher` from the terminal and I got an error related to `gtk` and themes.
- I installed version `5.17.4` from source with `python setup.py install`

### Log output

```shell
2022-09-13 14:20:02,126 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 28, in <module>
    main()
  File "/usr/lib64/python3.9/site-packages/ulauncher/main.py", line 136, in main
    window = UlauncherWindow.get_instance()
  File "/usr/lib64/python3.9/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 56, in get_instance
    return cls()
  File "/usr/lib64/python3.9/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 66, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib64/python3.9/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 99, in finish_initializing
    self.init_theme()
  File "/usr/lib64/python3.9/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 231, in init_theme
    load_available_themes()
  File "/usr/lib64/python3.9/site-packages/ulauncher/utils/Theme.py", line 28, in load_available_themes
    theme.validate()
  File "/usr/lib64/python3.9/site-packages/ulauncher/utils/Theme.py", line 94, in validate
    assert self.get_css_file_gtk_3_20(), '"css_file_gtk_3.20+" is empty'
  File "/usr/lib64/python3.9/site-packages/ulauncher/utils/Theme.py", line 73, in get_css_file_gtk_3_20
    return self._read()['css_file_gtk_3.20+']
KeyError: 'css_file_gtk_3.20+'
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
The theme needs to specify `css_file_gtk_3.20+` http://docs.ulauncher.io/en/latest/themes/themes.html

If shouldn't break for missing it of course.

**Comment by friday** [comment]
Should be fixed now in the v5 branch ^ Going to do a bigger theme rehaul for the v6 branch.
