### ISSUE TITLE
I can't install any extension (There's an error in versions.json:)

### ISSUE THREAD

**Issue by hrqmonteiro** [Ulauncher/Ulauncher#1132]
### Environment

Fedora 36

### Bug description

I can´t install ANY extensions, everytime i try one, i get this error:

```
There's an error in versions.json: 
Branch/commit "master" does not exist.

Let the author know about this problem via [Github issues](file2:///usr/share/ulauncher/preferences/dist/index.html).
```

![Screenshot from 2022-09-27 00-20-58](https://user-images.githubusercontent.com/17055027/192424319-0705f8ba-9c13-43ea-851e-f47897a7accd.png)

### Log output

```shell
[hrq@fedora ~]$ ulauncher -v
2022-09-27 00:21:20,332 | INFO | ulauncher: main() | Ulauncher version 5.14.7
2022-09-27 00:21:20,332 | INFO | ulauncher: main() | Extension API version 2.0.0
2022-09-27 00:21:20,332 | INFO | ulauncher: main() | GTK+ 3.24.34
2022-09-27 00:21:20,332 | INFO | ulauncher: main() | Is Wayland: True
2022-09-27 00:21:20,332 | INFO | ulauncher: main() | Wayland compatibility: on
2022-09-27 00:21:20,347 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-09-27 00:21:20,350 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2022-09-27 00:21:20,350 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-09-27 00:21:20,350 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-09-27 00:21:20,351 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-09-27 00:21:20,351 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-09-27 00:21:20,352 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-09-27 00:21:20,352 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2022-09-27 00:21:20,352 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-09-27 00:21:20,352 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2022-09-27 00:21:20,353 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-09-27 00:21:20,353 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-09-27 00:21:20,361 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-09-27 00:21:20,362 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2022-09-27 00:21:20,362 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2022-09-27 00:21:20,375 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.tchar.ulauncher-albert-calculate-anything" started. PID 191824
2022-09-27 00:21:20,377 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ulauncher.ulauncher-emoji" started. PID 191826
2022-09-27 00:21:20,379 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.manahter.ulauncher-translate" started. PID 191828
2022-09-27 00:21:20,382 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ulauncher.ulauncher-timer" started. PID 191831
2022-09-27 00:21:20,383 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.the-lay.ulauncher-spotify-api" started. PID 191833
2022-09-27 00:21:20,411 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 61 apps in cache
2022-09-27 00:21:20,413 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-devdocs" started. PID 191834
2022-09-27 00:21:20,441 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.jetbug123.ulauncher-ssh" started. PID 191838
2022-09-27 00:21:20,451 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-docker" started. PID 191839
2022-09-27 00:21:20,453 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/evolution-calendar.desktop": constructor returned NULL
2022-09-27 00:21:20,454 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-vscode-projects" started. PID 191841
2022-09-27 00:21:20,463 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.nortmas.chrome-bookmarks" started. PID 191843
2022-09-27 00:21:20,472 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.dhelmr.ulauncher-duckduckgo-bangs" started. PID 191844
2022-09-27 00:21:20,475 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 61 apps in the system
2022-09-27 00:21:20,475 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.11 seconds
2022-09-27 00:21:20,504 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hillaryychan.ulauncher-fzf" started. PID 191851
2022-09-27 00:21:20,518 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2022-09-27 00:21:20,527 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.mikebarkmin.ulauncher-duckduckgo" started. PID 191859
2022-09-27 00:21:20,549 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.elken.terminal-runner" started. PID 191862
2022-09-27 00:21:20,550 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.fajtak.ulauncher-weather" started. PID 191864
2022-09-27 00:21:20,577 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.nastuzzisamy.ulauncher-youtube-search" started. PID 191875
2022-09-27 00:21:20,578 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.glovecc.ulauncher-github-search" started. PID 191869
Traceback (most recent call last):
  File "/home/hrq/.local/share/ulauncher/extensions/com.github.brpaz.ulauncher-docker/main.py", line 6, in <module>
    from dk.extension import DockerExtension
  File "/home/hrq/.local/share/ulauncher/extensions/com.github.brpaz.ulauncher-docker/dk/extension.py", line 8, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'
2022-09-27 00:21:20,627 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.safaariman.ulauncher-jira" started. PID 191884
2022-09-27 00:21:20,628 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-docker" exited instantly with code 1
2022-09-27 00:21:20,628 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-docker" failed with an error: ModuleNotFoundError: No module named 'docker'


(ulauncher:191812): Gtk-CRITICAL **: 00:21:20.801: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
2022-09-27 00:21:20,921 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.the-lay.ulauncher-spotify-api" connected
2022-09-27 00:21:20,921 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.the-lay.ulauncher-spotify-api"
com.github.the-lay.ulauncher-spotify-api | 2022-09-27 00:21:20,922 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
com.github.the-lay.ulauncher-spotify-api | 2022-09-27 00:21:20,922 | DEBUG | __main__: on_event() | Extension language is: en. Searching translation files in /home/hrq/.local/share/ulauncher/extensions/com.github.the-lay.ulauncher-spotify-api/locales.
com.github.the-lay.ulauncher-spotify-api | 2022-09-27 00:21:20,922 | DEBUG | __main__: on_preferences() | Received preferences event: {'main_keyword': 'sp', 'main_language': 'en', 'auth_port': '8080', 'clear_cache': 'No', 'show_help': 'Yes', 'aliases': 's: search; song: track; vol: volume; like: save; ?: help', 'search_results_limit': '8', 'request_timeout': '0.5'}
com.github.the-lay.ulauncher-spotify-api | 2022-09-27 00:21:20,922 | DEBUG | __main__: _generate_api() | Generating Spotipy object
com.github.the-lay.ulauncher-spotify-api | 2022-09-27 00:21:20,923 | DEBUG | __main__: _generate_aliases() | Generating aliases
2022-09-27 00:21:20,955 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.ulauncher.ulauncher-emoji" connected
2022-09-27 00:21:20,955 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.ulauncher.ulauncher-emoji"
com.github.ulauncher.ulauncher-emoji | 2022-09-27 00:21:20,956 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:20,987 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.dhelmr.ulauncher-duckduckgo-bangs" connected
2022-09-27 00:21:20,987 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.dhelmr.ulauncher-duckduckgo-bangs"
com.github.dhelmr.ulauncher-duckduckgo-bangs | 2022-09-27 00:21:20,988 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:20,999 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.tchar.ulauncher-albert-calculate-anything" connected
2022-09-27 00:21:21,000 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.tchar.ulauncher-albert-calculate-anything"
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,001 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,001 | INFO | calculate_anything.utils.misc: safe_operation() | Set language
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,001 | INFO | calculate_anything.utils.misc: safe_operation() | Set default cities
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,002 | INFO | calculate_anything.utils.misc: safe_operation() | Set units conversion mode
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,002 | INFO | calculate_anything.utils.misc: safe_operation() | Set currency providers
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,002 | INFO | calculate_anything.utils.misc: safe_operation() | Set cache interval
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,002 | INFO | calculate_anything.utils.misc: safe_operation() | Set default currencies
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,003 | INFO | calculate_anything.utils.misc: safe_operation() | LanguagePreferences: lang = en_US
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,003 | INFO | calculate_anything.utils.misc: safe_operation() | TimePreferences: default_cities = [('new york city', 'US'), ('london', 'GB'), ('madrid', 'ES'), ('vancouver', 'CA'), ('athens', 'GR')]
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,003 | INFO | calculate_anything.utils.loaders.sqlite: _load() | Loaded timezone database: /home/hrq/.cache/com.github.tchar.calculate-anything/timezones.sqlite3
2022-09-27 00:21:21,021 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.manahter.ulauncher-translate" connected
2022-09-27 00:21:21,022 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.manahter.ulauncher-translate"
com.github.manahter.ulauncher-translate | 2022-09-27 00:21:21,023 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,044 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.ulauncher.ulauncher-timer" connected
2022-09-27 00:21:21,044 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.ulauncher.ulauncher-timer"
com.github.ulauncher.ulauncher-timer | 2022-09-27 00:21:21,045 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,084 | INFO | calculate_anything.utils.misc: safe_operation() | UnitsPreferences: units_conversion_mode = ConversionMode.NORMAL
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,085 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: add_provider = <calculate_anything.currency.providers.fixerio.FixerIOCurrencyProvider object at 0x7f0f57b1ac50>
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,085 | INFO | calculate_anything.currency.service: remove_provider() | Removing provider FixerIOCurrencyProvider
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,085 | INFO | calculate_anything.currency.service: add_provider() | Adding provider FixerIOCurrencyProvider
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,085 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: cache_update_frequency = 86400
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,085 | INFO | calculate_anything.currency.service: enable_cache() | Enabling cache with update frequency = 86400
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,086 | INFO | calculate_anything.currency.cache: enable() | Enabling cache every 86400s
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,086 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: default_currencies = ['USD', 'EUR', 'GBP', 'CAD']
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,086 | INFO | calculate_anything.currency.service: set_default_currencies() | Updating default currencies = ['USD', 'EUR', 'GBP', 'CAD']
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,086 | INFO | calculate_anything.currency.service: start() | Currency Service is running
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,086 | INFO | calculate_anything.currency.service.UpdateThread(id=348850e4b405): run() | Starting thread
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-27 00:21:21,088 | INFO | calculate_anything.currency.service.UpdateThread(id=348850e4b405): run() | Sleeping for 85237s
2022-09-27 00:21:21,101 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.brpaz.ulauncher-vscode-projects" connected
2022-09-27 00:21:21,102 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.brpaz.ulauncher-vscode-projects"
com.github.brpaz.ulauncher-vscode-projects | 2022-09-27 00:21:21,103 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,129 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.jetbug123.ulauncher-ssh" connected
2022-09-27 00:21:21,130 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.jetbug123.ulauncher-ssh"
com.github.jetbug123.ulauncher-ssh | 2022-09-27 00:21:21,131 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,162 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.brpaz.ulauncher-devdocs" connected
2022-09-27 00:21:21,166 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.brpaz.ulauncher-devdocs"
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:21,167 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:21,167 | INFO | __main__: index() | Start indexing documentation
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:21,169 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
/var/lib/plocate/plocate.db: No such file or directory
2022-09-27 00:21:21,179 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.nastuzzisamy.ulauncher-youtube-search" connected
2022-09-27 00:21:21,179 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.nastuzzisamy.ulauncher-youtube-search"
com.github.nastuzzisamy.ulauncher-youtube-search | 2022-09-27 00:21:21,180 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
/var/lib/plocate/plocate.db: No such file or directory
2022-09-27 00:21:21,209 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.hillaryychan.ulauncher-fzf" connected
2022-09-27 00:21:21,210 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.hillaryychan.ulauncher-fzf"
com.github.hillaryychan.ulauncher-fzf | 2022-09-27 00:21:21,211 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
/var/lib/plocate/plocate.db: No such file or directory
ERROR:ChromeBookmarks:Path to the Chrome Bookmarks was not found
2022-09-27 00:21:21,236 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.nortmas.chrome-bookmarks" connected
2022-09-27 00:21:21,236 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.nortmas.chrome-bookmarks"
NoneType: None
DEBUG:ulauncher.api.client.Client:Incoming event PreferencesEvent
com.github.nortmas.chrome-bookmarks | 2022-09-27 00:21:21,237 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,253 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.fajtak.ulauncher-weather" connected
2022-09-27 00:21:21,254 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.fajtak.ulauncher-weather"
com.github.fajtak.ulauncher-weather | 2022-09-27 00:21:21,254 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,312 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.elken.terminal-runner" connected
2022-09-27 00:21:21,312 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.elken.terminal-runner"
com.github.elken.terminal-runner | 2022-09-27 00:21:21,313 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,323 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.mikebarkmin.ulauncher-duckduckgo" connected
2022-09-27 00:21:21,323 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.mikebarkmin.ulauncher-duckduckgo"
com.github.mikebarkmin.ulauncher-duckduckgo | 2022-09-27 00:21:21,324 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,333 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.safaariman.ulauncher-jira" connected
2022-09-27 00:21:21,333 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.safaariman.ulauncher-jira"
com.github.safaariman.ulauncher-jira | 2022-09-27 00:21:21,334 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-27 00:21:21,379 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.glovecc.ulauncher-github-search" connected
2022-09-27 00:21:21,379 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.glovecc.ulauncher-github-search"
com.github.glovecc.ulauncher-github-search | 2022-09-27 00:21:21,380 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:21,828 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/docs.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:21,944 | INFO | __main__: fetch_doc_entries() | Fetching Docs for c 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:21,945 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:22,557 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/c/index.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:23,066 | INFO | __main__: fetch_doc_entries() | Fetching Docs for d 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:23,067 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:23,844 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/d/index.json HTTP/1.1" 200 None
2022-09-27 00:21:24,035 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2022-09-27 00:21:24,045 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2022-09-27 00:21:24,045 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2022-09-27 00:21:24,186 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2022-09-27 00:21:24,186 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2022-09-27 00:21:24,189 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2022-09-27 00:21:24,190 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2022-09-27 00:21:24,693 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:24,706 | INFO | __main__: fetch_doc_entries() | Fetching Docs for git 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:24,707 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:25,405 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/git/index.json HTTP/1.1" 200 None
2022-09-27 00:21:25,747 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_get_all() | Handling /extension/get-all
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:25,911 | INFO | __main__: fetch_doc_entries() | Fetching Docs for go 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:25,912 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:26,658 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/go/index.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:27,372 | INFO | __main__: fetch_doc_entries() | Fetching Docs for javascript 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:27,374 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:28,000 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/javascript/index.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:28,525 | INFO | __main__: fetch_doc_entries() | Fetching Docs for markdown 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:28,527 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:29,206 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/markdown/index.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:29,711 | INFO | __main__: fetch_doc_entries() | Fetching Docs for node 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:29,715 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:30,443 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/node/index.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:31,137 | INFO | __main__: fetch_doc_entries() | Fetching Docs for php 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:31,141 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:31,887 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/php/index.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:32,728 | INFO | __main__: fetch_doc_entries() | Fetching Docs for r 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:32,731 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:33,426 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/r/index.json HTTP/1.1" 200 None
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:34,217 | INFO | __main__: fetch_doc_entries() | Fetching Docs for ruby~2.5 
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:34,221 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTPS connection (1): devdocs.io:443
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:34,924 | DEBUG | urllib3.connectionpool: _make_request() | https://devdocs.io:443 "GET /docs/ruby~2.5/index.json HTTP/1.1" 200 None
2022-09-27 00:21:35,333 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://github.com/NCRoxas/coingecko-query
2022-09-27 00:21:35,588 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | GithubExtensionError: Branch/commit "master" does not exist.
com.github.brpaz.ulauncher-devdocs | 2022-09-27 00:21:35,755 | INFO | __main__: index() |
```
```


### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by Bananaman** [comment]
@hrqmonteiro You use `Ulauncher version 5.14.7`

There is https://github.com/Ulauncher/Ulauncher/releases/tag/5.15.0 from 11 days ago (a week before your ticket), with this change:

- "Ulauncher will no longer assume the default extension branch is named "master""

```
$ dnf if ulauncher

Name         : ulauncher
Version      : 5.15.0
Release      : 1.fc36
Architecture : noarch
Size         : 1.5 M
Source       : ulauncher-5.15.0-1.fc36.src.rpm
Repository   : updates
Summary      : Linux Application Launcher
URL          : https://github.com/Ulauncher/Ulauncher
License      : GPLv3+
Description  : Ulauncher is a fast application launcher for Linux. It's is
             : written in Python, using GTK+.
```

Try updating your system.

**Comment by friday** [comment]
Yeah. The fedora releases have a routine where they have to be in "testing" for a week or something before they are actually pushed out to users (simplified explanation), so he had the latest version for his distro at the time.

Closing the issue since it's out now.

**Comment by AdrianCarreno** [comment]
I apologize for reopening this issue, but I have the same issue with Ulauncher v.5.15.1. I tried installing [Onetimepass extension](https://github.com/zirosas/onetimepass-ulauncher) (which has only one branch, called `main`) and U launcher can't install it.

Environment:
- Elementary OS 6.1 (built on Ubuntu 20.04.5 LTS)
- Ulauncher v5.15.1, Extension API v2.0.0

**Comment by assada** [comment]
Same issue with ubuntu 20.04 and Ulauncher 5.15.3

**Comment by gunererd** [comment]
Having same issue when installing [ulauncher-youtube-search]( https://github.com/NastuzziSamy/ulauncher-youtube-search)

ulauncher 5.15.6

**Comment by friday** [comment]
This issue was fixed a long time ago. If you can't install a specific extension see #767
