### ISSUE TITLE
422 error while adding extension

### ISSUE THREAD

**Issue by xRealNeon** [Ulauncher/Ulauncher#1165]
### Environment

Ubuntu 20.04.5 LTS x86_64 5.4.0-92-generic | Ulauncher v5.8.0

### Bug description

I can't add my extension to Ulauncher it gives me a `422` HTTP error.
I can add other extension but not this one. 
I have tried to add this extension to the extension registry, but I also get an error, see [here](https://github.com/Ulauncher/ext-api.ulauncher.io/issues/18)

Link to the extension:
[https://github.com/xRealNeon/SpritpreiseUlauncher](https://github.com/xRealNeon/SpritpreiseUlauncher)

### Log output

```shell
2022-12-14 12:57:48,656 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. HTTPError: HTTP Error 422: Unprocessable Entity
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 425, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 80, in find_compatible_version
    return self.get_commit(sha_or_branch)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 89, in get_commit
    resp = json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by xRealNeon** [comment]
Fixed it https://github.com/xRealNeon/SpritpreiseUlauncher/commit/055bbf22b157c7a8282ae2c0b40ab2d95636b7c1
