### ISSUE TITLE
Ulauncher stopped showing apps

### ISSUE THREAD

**Issue by LogicWrite** [Ulauncher/Ulauncher#1185]
### Environment

Xubuntu

### Bug description

After an update the launcher stopped showing any app. Not sure what to do to reproduce. Tried reinstalling ulauncher but it didn't work. On each key press ulauncher would log this:

### Log output

```shell
2023-01-12 10:29:02,492 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 298, in toggle_window
    self.show_window()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 288, in show_window
    self.show_results([])
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 370, in show_results
    result_items = AppStatDb.get_instance().get_most_frequent(recent_apps_number)
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppStatDb.py", line 40, in get_most_frequent
    return [AppResultItem(i) for i in islice(
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppStatDb.py", line 40, in <listcomp>
    return [AppResultItem(i) for i in islice(
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppResultItem.py", line 15, in __init__
    self._query_history = QueryHistoryDb.get_instance()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/QueryHistoryDb.py", line 13, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 37, in open
    self.set_records(pickle.load(_in))
_pickle.UnpicklingError: pickle data was truncated
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
https://github.com/Ulauncher/Ulauncher/issues/699#issuecomment-993457876
