### ISSUE TITLE
Unable to start on X11 with fractional scaling enabled

### ISSUE THREAD

**Issue by theotherp** [Ulauncher/Ulauncher#1248]
### Environment

Ubuntu 23.04, X11, ulauncher 5.15.2

### Bug description

I have a 32" 4K monitor and fractional scaling enabled (150%). With this I'm unable to run ulauncher. Going to 100% fixes this.

I'm not using Wayland (according to this code I found online, I'm not a linux expert):
```
➜  ulauncher git:(v6) echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
```

FWIW, you're not alone with this, I'm having problems with loads of apps.

### Log output

```shell
5.15.5:

2023-07-17 08:05:52,256 | INFO | ulauncher: main() | Ulauncher version 5.15.2
2023-07-17 08:05:52,256 | INFO | ulauncher: main() | Extension API version 2.0.0
2023-07-17 08:05:52,256 | INFO | ulauncher: main() | GTK+ 3.24.37
2023-07-17 08:05:52,256 | INFO | ulauncher: main() | Is Wayland: False
2023-07-17 08:05:52,256 | INFO | ulauncher: main() | Wayland compatibility: off
2023-07-17 08:05:52,265 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2023-07-17 08:05:52,266 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2023-07-17 08:05:52,267 | DEBUG | ulauncher.utils.display: get_screens() | Found 3 monitor(s)
2023-07-17 08:05:52,268 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 1920, Y: 720, W: 2560, H: 1440
2023-07-17 08:05:52,268 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 4480, Y: 0, W: 3840, H: 2160
2023-07-17 08:05:52,268 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 2 - X: 0, Y: 960, W: 1920, H: 1200
2023-07-17 08:05:52,271 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 136, in main
    window = UlauncherWindow.get_instance()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 56, in get_instance
    return cls()
           ^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 66, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 99, in finish_initializing
    self.init_theme()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 242, in init_theme
    self._render_prefs_icon()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 393, in _render_prefs_icon
    surface = Gdk.cairo_surface_create_from_pixbuf(prefs_pixbuf, scale_factor, self.get_window())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cairo.Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```

https://github.com/Ulauncher/Ulauncher/commit/32dc199029495105a5065b035135b4bfef28a1bc:
```
➜  ulauncher git:(v6) ./bin/ulauncher -v
Failed to load GtkLayerShell, disabling positioning on wayland!
running build_prefs
Detected no changes to Preferences since last build.
2023-07-17 08:15:01,348 ℹ️  INFO Ulauncher version 6.0.0 main.main:64
2023-07-17 08:15:01,348 ℹ️  INFO Extension API version 3.0 main.main:65
2023-07-17 08:15:01,348 ℹ️  INFO GTK+ 3.24.37 main.main:66
2023-07-17 08:15:01,348 ℹ️  INFO PyGObject+ 3.44.1 main.main:67
2023-07-17 08:15:01,348 ℹ️  INFO Desktop: ubuntu:GNOME (X11) on Ubuntu 23.04 main.main:69
2023-07-17 08:15:01,353 ℹ️  DEBUG Removing existing socket path /run/user/1000/ulauncher_control ExtensionServer.start:38
2023-07-17 08:15:01,363 ℹ️  INFO Wayland layer shell extension: not supported LayerShell.is_supported:32
2023-07-17 08:15:01,373 ⚠️  WARNING Could not load specified icon /home/simon/apps/ulauncher/data/icons/gear.svg (invalid value (typically too big) for the size of the input (surface, pattern, etc.)). Will use fallback icon icon.load_icon_surface:57
2023-07-17 08:15:01,373 ⚠️  ERROR Uncaught exception main.except_hook:80
Traceback (most recent call last):
  File "/home/simon/apps/ulauncher/ulauncher/utils/icon.py", line 51, in load_icon_surface
    return Gdk.cairo_surface_create_from_pixbuf(pixbuf, scaling_factor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cairo.Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/apps/ulauncher/ulauncher/utils/icon.py", line 51, in load_icon_surface
    return Gdk.cairo_surface_create_from_pixbuf(pixbuf, scaling_factor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cairo.Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simon/apps/ulauncher/ulauncher/ui/UlauncherApp.py", line 62, in do_activate
    self.show_launcher()
  File "/home/simon/apps/ulauncher/ulauncher/ui/UlauncherApp.py", line 106, in show_launcher
    self.window = UlauncherWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/apps/ulauncher/ulauncher/ui/windows/UlauncherWindow.py", line 171, in __init__
    prefs_icon_surface = load_icon_surface(f"{PATHS.ASSETS}/icons/gear.svg", 16, self.get_scale_factor())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/apps/ulauncher/ulauncher/utils/icon.py", line 58, in load_icon_surface
    return load_icon_surface(DEFAULT_EXE_ICON, size, scaling_factor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/apps/ulauncher/ulauncher/utils/icon.py", line 55, in load_icon_surface
    raise RuntimeError(msg) from e
RuntimeError: Could not load fallback icon: /home/simon/apps/ulauncher/data/icons/executable.png
2023-07-17 08:15:01,378 ℹ️  INFO Trying to bind app hotkey: <Primary>space UlauncherApp.bind_hotkey:97
```
```


### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
> FWIW, you're not alone with this, I'm having problems with loads of apps.

It's because it's GTK crashing.

We can't really debug this. We also can't switch to GTK 4 because they dropped support for lots of things we use. If you need this fixed, then you could try how big the scaling factor value is allowed to be and if it looks decent when you limit it to that (https://docs.python.org/3/library/functions.html#max).
