### ISSUE TITLE
Error Creating Demo Extension Following Developer Guide

### ISSUE THREAD

**Issue by pbragamiranda** [Ulauncher/Ulauncher#1328]
### Environment

Ubuntu 22.04.3 LTS

### Bug description

Hi everyone,

I'm trying to create my first extension following the [development tutorial](https://docs.ulauncher.io/en/stable/extensions/tutorial.html#custom-action-on-item-enter) but running into issues.

After copying the code to `main.py`, I attempted to run the file using the recommended [Debugging & Logging](https://docs.ulauncher.io/en/stable/extensions/debugging.html) approach, but I encountered an error.

I've looked into the `extension.py` class in the [Ulauncher repository](https://github.com/Ulauncher/Ulauncher) for debugging, but I didn't have much luck.

Here are my logs:

```bash
VERBOSE=1 ULAUNCHER_WS_API=ws://127.0.0.1:5054 python3 ~/.local/share/ulauncher/extensions/kagi-search/main.py
```

```
kagi-search | 2023-12-04 21:46:18,674 | ERROR | ulauncher.api.client.Client: on_error() | WS Client error Connection to the remote host was lost.
kagi-search | 2023-12-04 21:46:18,674 | ERROR | websocket: error() | error from callback <function Client.connect.<locals>.<lambda> at 0x7f78dce34670>: Client.connect.<locals>.<lambda>() takes 1 positional argument but 3 were given
kagi-search | 2023-12-04 21:46:18,674 | ERROR | ulauncher.api.client.Client: on_error() | WS Client error Client.connect.<locals>.<lambda>() takes 1 positional argument but 3 were given
```

python3 -V
```
Python 3.10.12
```

thanks in advance!

### Log output

```shell
kagi-search | 2023-12-04 21:46:18,674 | ERROR | ulauncher.api.client.Client: on_error() | WS Client error Connection to the remote host was lost.
kagi-search | 2023-12-04 21:46:18,674 | ERROR | websocket: error() | error from callback <function Client.connect.<locals>.<lambda> at 0x7f78dce34670>: Client.connect.<locals>.<lambda>() takes 1 positional argument but 3 were given
kagi-search | 2023-12-04 21:46:18,674 | ERROR | ulauncher.api.client.Client: on_error() | WS Client error Client.connect.<locals>.<lambda>() takes 1 positional argument but 3 were given
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
It's probably because of #1274.

You can copy your extension to ~/.local/share/ulauncher/extensions/your-extension
Then kill ulauncher (`systemctl --user stop ulauncher` if you are using systemd) and run ` ulauncher -v --dev` in a terminal to get log output.

Also see #869. This is all changed now for v6. I never used the documented way and it's now unsupported/removed in v6 which will basically do the above but in more convenient ways without requiring restarts.

**Comment by pbragamiranda** [comment]
Hey, @friday. Thanks for your reply. 

I'm able to get the logs output when I run ` ulauncher -v --dev`. My problem is when I try to run the basic example extension listed on the development tutorial.

When I run: ` VERBOSE=1 ULAUNCHER_WS_API=ws://127.0.0.1:5054 python3 ~/.local/share/ulauncher/extensions/kagi-search/main.py`

I get: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/utils/SimpleWebSocketServer.py", line 273, in _handleData
    self.handleConnected()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionController.py", line 98, in handleConnected
    raise Exception('Incorrect path %s' % self.request.path)
Exception: Incorrect path /

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/utils/SimpleWebSocketServer.py", line 659, in serveforever
    client._handleData()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/SimpleWebSocketServer.py", line 275, in _handleData
    raise Exception('handshake failed: %s' % e) from e
Exception: handshake failed: Incorrect path /

**Comment by friday** [comment]
Fixed in 6a806ef4 (released as v5.16.0 a week ago)
