### ISSUE TITLE
Ulauncher fails to start with exception : gdk-pixbuf-error-quark couldn't recognise svg format.

### ISSUE THREAD

**Issue by UbiquitousPhoton** [Ulauncher/Ulauncher#1331]
### Environment

Manjaro KDE (Wayland) : KDE Plasma Version: 5.27.10 : KDE Frameworks Version: 5.113.0 : Qt Version: 5.15.11 : Kernel Version: 6.6.8-2-MANJARO (64-bit)

### Bug description

After running a system upgrade, Ulauncher fails to launch. This is a duplicate of an old bug [here](https://github.com/Ulauncher/Ulauncher/issues/758) from 2021, which was closed without resolution. This error appears to happen however I start ULauncher.

I have clean rebuilt, but still get the same error. The file in question is definitely an svg.

### Log output

```shell
2024-01-03 22:53:22,826 | INFO | ulauncher: main() | Ulauncher version 5.15.6
2024-01-03 22:53:22,826 | INFO | ulauncher: main() | Extension API version 2.0.0
2024-01-03 22:53:22,827 | INFO | ulauncher: main() | GTK+ 3.24.39
2024-01-03 22:53:22,827 | INFO | ulauncher: main() | Is Wayland: True
2024-01-03 22:53:22,827 | INFO | ulauncher: main() | Wayland compatibility: on
2024-01-03 22:53:22,837 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2024-01-03 22:53:22,839 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2024-01-03 22:53:22,839 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2024-01-03 22:53:22,839 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2024-01-03 22:53:22,840 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2024-01-03 22:53:22,840 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2024-01-03 22:53:22,840 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2024-01-03 22:53:22,840 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2024-01-03 22:53:22,840 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2024-01-03 22:53:22,840 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2024-01-03 22:53:22,841 | DEBUG | ulauncher.utils.display: get_screens() | Found 2 monitor(s)
2024-01-03 22:53:22,841 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 2560, Y: 0, W: 2560, H: 1440
2024-01-03 22:53:22,841 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 0, Y: 0, W: 2560, H: 1440
2024-01-03 22:53:22,843 | WARNING | ulauncher.utils.image_loader: load_image() | Could not load image /usr/share/ulauncher/media/gear.svg. E: gdk-pixbuf-error-quark: Couldn’t recognise the image file format for file “/usr/share/ulauncher/media/gear.svg” (3)
2024-01-03 22:53:22,843 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 28, in <module>
    main()
  File "/usr/lib/python3.11/site-packages/ulauncher/main.py", line 136, in main
    window = UlauncherWindow.get_instance()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 56, in get_instance
    return cls()
           ^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 66, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 99, in finish_initializing
    self.init_theme()
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 242, in init_theme
    self._render_prefs_icon()
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 393, in _render_prefs_icon
    surface = Gdk.cairo_surface_create_from_pixbuf(prefs_pixbuf, scale_factor, self.get_window())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 0 does not allow None as a value
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by UbiquitousPhoton** [comment]
Many thanks @friday - this solved it. For future people, on Arch/Manjaro you only need do:

```shell
sudo update-mime-database /usr/share/mime
sudo gdk-pixbuf-query-loaders --update-cache
```
(No need to specify full path for `gdk-pixbuf-query-loaders` ) 

Hint: you can use `which gdk-pixbuf-query-loaders` to find the path if you need to supply full path on your system.

**Comment by friday** [comment]
@UbiquitousPhoton (unrelated to the topic). Since you're the only one I saw using KDE Wayland, I'm curious if you have fond a way around #1261 or if you don't have this issue?

**Comment by UbiquitousPhoton** [comment]
> @UbiquitousPhoton (unrelated to the topic). Since you're the only one I saw using KDE Wayland, I'm curious if you have found a way around #1261 or if you don't have this issue?

Apologies, I missed this - I don't get this issue when I launch from the gui, or from auto-start, but I *do* get it when launching from console, which is admittedly kinda curious. Happy to do more testing if you want me to.

**Comment by friday** [comment]
> I don't get this issue when I launch from the gui, or from auto-start, but I _do_ get it when launching from console, which is admittedly kinda curious. Happy to do more testing if you want me to.

Thank you :+1: That is good to know. I have to test this some time.
