### ISSUE TITLE
Double applet icons in Linux Mint

### ISSUE THREAD

**Issue by Boyfinn** [Ulauncher/Ulauncher#1389]
### Environment

Linux Mint 21.3

### Bug description

Ulauncher applet icon shows up twice in the applet tray. I've gone to the applet settings panel and made sure Ulauncher doesn't appear there twice. (In fact, it doesn't appear there at all).
![image](https://github.com/Ulauncher/Ulauncher/assets/33183150/b8f31fd9-e9a6-458c-aaa1-de0bbefb2ddd)

Steps to reproduce:
1. Install Ulauncher system package from apt
2. Enable "Launch at login" from settings
3. After a couple reboots, a second Ulauncher applet appears in the applet tray. Both function the same when clicking. Exiting one exits both.
For some reason this never occurs to me after a single reboot after installing the package. It often takes a couple reboots before the second icon appears.

OS: Linux Mint 21.3 x86_64
Kernel: 6.5.0-1020-oem 
Desktop: Cinnamon 6.0.4
Ulauncher: V5.15.6
Ext.API: V2.0.0

### Log output

```shell
2024-05-06 15:12:26,795 | INFO | ulauncher: main() | Ulauncher version 5.15.6
2024-05-06 15:12:26,795 | INFO | ulauncher: main() | Extension API version 2.0.0
2024-05-06 15:12:26,795 | INFO | ulauncher: main() | GTK+ 3.24.33
2024-05-06 15:12:26,795 | INFO | ulauncher: main() | Is Wayland: False
2024-05-06 15:12:26,795 | INFO | ulauncher: main() | Wayland compatibility: off
2024-05-06 15:12:26,812 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2024-05-06 15:12:26,814 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2024-05-06 15:12:26,815 | DEBUG | ulauncher.utils.display: get_screens() | Found 2 monitor(s)
2024-05-06 15:12:26,815 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 480, W: 2560, H: 1440
2024-05-06 15:12:26,815 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 2560, Y: 0, W: 1080, H: 1920
2024-05-06 15:12:26,853 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2024-05-06 15:12:26,854 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2024-05-06 15:12:26,854 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2024-05-06 15:12:26,870 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Alt>space
2024-05-06 15:12:26,870 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 151 apps in cache
2024-05-06 15:12:26,877 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/vim.desktop": constructor returned NULL
2024-05-06 15:12:26,884 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 151 apps in the system
2024-05-06 15:12:26,884 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.03 seconds
2024-05-06 15:12:26,896 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2024-05-06 15:31:59,189 | DEBUG | ulauncher.utils.display: get_screens() | Found 2 monitor(s)
2024-05-06 15:31:59,189 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 480, W: 2560, H: 1440
2024-05-06 15:31:59,189 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 2560, Y: 0, W: 1080, H: 1920
2024-05-06 15:31:59,189 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2024-05-06 15:32:00,634 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 183, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 23, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 38, in open
    records = pickle.load(reader)
EOFError: Ran out of input
2024-05-06 15:32:00,636 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 175, in on_input_changed
    Search.get_instance().on_query_change(self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 23, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 38, in open
    records = pickle.load(reader)
EOFError: Ran out of input
2024-05-06 15:32:00,791 | WARNING | ulauncher.utils.image_loader: check_icon_name() | Icon theme is broken or incomplete. Substituting "vscode" for "vscode"
2024-05-06 15:32:00,834 | WARNING | ulauncher.utils.image_loader: check_icon_name() | Icon "software-properties-mint" completely missing from icon theme. Consider switching icon theme.
2024-05-06 15:32:00,834 | INFO | ulauncher.utils.image_loader: check_icon_name() | Falling back on default icon "application-x-executable"
2024-05-06 15:32:00,839 | WARNING | ulauncher.utils.image_loader: check_icon_name() | Icon theme is broken or incomplete. Substituting "plasticity" for "plasticity"
2024-05-06 15:32:00,867 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results
2024-05-06 15:32:00,964 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 6 results
2024-05-06 15:32:01,098 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 7 results
2024-05-06 15:32:01,196 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 6 results
2024-05-06 15:32:01,305 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 3 results
2024-05-06 15:32:01,405 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 4 results
2024-05-06 15:32:01,504 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 2 results
2024-05-06 15:32:02,849 | INFO | ulauncher.api.shared.action.LaunchAppAction: run() | Run application Screenshot (/usr/share/applications/org.gnome.Screenshot.desktop) Exec ['gapplication', 'launch', 'org.gnome.Screenshot']
2024-05-06 15:32:02,855 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2024-05-06 15:34:33,477 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2024-05-06 15:34:33,481 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2024-05-06 15:34:33,481 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2024-05-06 15:34:33,673 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2024-05-06 15:34:33,673 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2024-05-06 15:34:33,674 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2024-05-06 15:34:33,675 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2024-05-06 15:34:34,035 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2024-05-06 15:35:58,557 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_close() | Close preferences
2024-05-06 15:36:28,972 | DEBUG | ulauncher.utils.display: get_screens() | Found 2 monitor(s)
2024-05-06 15:36:28,972 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 480, W: 2560, H: 1440
2024-05-06 15:36:28,972 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 2560, Y: 0, W: 1080, H: 1920
2024-05-06 15:36:28,972 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
- [X] I have tried to understand the error message and help myself, before reporting it.
- [X] My issue description has clear steps for how to reproduce the issue.
- [X] This issue applies to the whole Ulauncher application, not for a specific extension.

### Ulauncher v6

- [ ] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
This is a Mint issue, not a Ulauncher issue. I created a Troubleshooting page for it instead, collecting the available info and digging in the LM issue trackers: https://github.com/Ulauncher/Ulauncher/discussions/1795
