### ISSUE TITLE
v6 beta fails to migrate some extensions

### ISSUE THREAD

**Issue by daveriedstra** [Ulauncher/Ulauncher#1403]
### Environment

Pop!_OS 22.04 Gnome on Wayland

### Bug description

Ulauncher v6 beta will not launch after upgrading from v5, instead it reports an error that it cannot find the `ulauncher-fzf` extension during the migration process.

What I did / repro:

- have a functional v5 install with various extensions
- install the ulauncher-dev PPA and upgrade to 6.0.0~beta14
- kill the previous version of ulauncher (which was still running)
- try to start the new version

Possibly relevant:

- `ulauncher-fzf` is not listed in `~/.config/ulauncher/extensions.json`
- `~/.local/share/ulauncher/extensions/com.github.hillaryychan.ulauncher.fzf` does not exist
  - manually cloning the repo to that dir allows the migration to continue for a few extensions, but it gets hung up on another extension
  - unfortunately I could not manually clone all these extensions because some repos no longer exist

Speculation:

- Ulauncher is attempting & failing to migrate disabled extensions based on `~/.config/ulauncher/ext_preferences` db files
  - Can I safely delete the db file from the corresponding problematic extension to try to get ulauncher up and running again?

### Log output

```shell
2024-07-08 11:04:22,590 | INFO | Ulauncher version 6.0.0-beta14 | main.main():53
2024-07-08 11:04:22,590 | INFO | Extension API version 3.0 | main.main():54
2024-07-08 11:04:22,591 | INFO | GTK+ 3.24.33 | main.main():55
2024-07-08 11:04:22,591 | INFO | PyGObject+ 3.42.1 | main.main():56
2024-07-08 11:04:22,591 | INFO | Desktop: POP:GNOME (WAYLAND) on Pop!_OS 22.04 LTS | main.main():58
2024-07-08 11:04:22,591 | WARNING | 

╔═════════════════════════════════════════════════════════════════════════════╗
║                  YOU ARE RUNNING A PRE-RELEASE of ULAUNCHER.                ║
║ Please do not report extension API support warnings to extension developers ║
║ We are still in the process of developing and documenting these features    ║
╚═════════════════════════════════════════════════════════════════════════════╝

 | main.main():60
2024-07-08 11:04:22,594 | INFO | Layer shell: No | main.main():71
2024-07-08 11:04:22,595 | INFO | X11 backend: No | main.main():72
2024-07-08 11:04:22,595 | INFO | Migrating /home/dried/.config/ulauncher/ext_preferences/com.github.hillaryychan.ulauncher-fzf.db to /home/dried/.config/ulauncher/ext_preferences/com.github.hillaryychan.ulauncher-fzf.json | migrate._migrate_file():50
2024-07-08 11:04:22,596 | ERROR | Uncaught exception | main.except_hook():80
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 48, in <module>
    main()
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 85, in main
    v5_to_v6()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/migrate.py", line 87, in v5_to_v6
    _migrate_file(str(file), f"{file.parent}/{file.stem}.json", partial(_migrate_user_prefs, file.stem))
  File "/usr/lib/python3/dist-packages/ulauncher/utils/migrate.py", line 52, in _migrate_file
    data = transform(data)
  File "/usr/lib/python3/dist-packages/ulauncher/utils/migrate.py", line 71, in _migrate_user_prefs
    if controller.manifest.triggers.get(id):
  File "/usr/lib/python3/dist-packages/ulauncher/modes/extensions/extension_controller.py", line 111, in manifest
    return ExtensionManifest.load(self.path)
  File "/usr/lib/python3/dist-packages/ulauncher/modes/extensions/extension_controller.py", line 117, in path
    assert self._path, f"No extension could be found matching {self.id}"
AssertionError: No extension could be found matching com.github.hillaryychan.ulauncher-fzf
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
- [X] I have tried to understand the error message and help myself, before reporting it.
- [X] My issue description has clear steps for how to reproduce the issue.
- [X] This issue applies to the whole Ulauncher application, not for a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Should be fixed now in v6 branch. Could you try it out to help me confirm before I make a release?

**Comment by daveriedstra** [comment]
Looks like it works! Thanks for addressing it so fast

**Comment by friday** [comment]
Awesome. Thank you for reporting it :+1:

**Comment by friday** [comment]
[v6.0.0-beta15](https://github.com/Ulauncher/Ulauncher/releases/tag/v6.0.0-beta15) just released with this fix.

The .debs are built by Launchpad and can take an hour or so before they're published
