### ISSUE TITLE
Ulauncher v6 systemd unit doesn't start on Gnome 47

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#1423]
### Environment

Arch  with Gnome 47

### Bug description

As of the latest system update Ulauncher no longer starts, but works after running `systemctl --user restart ulauncher`. Might also be AMD related because I'm having issues with AMD crashes when connected to an external screen.

Need to investigate.

### Log output

```shell
nov 20 10:30:39 rubacava ulauncher[3762]: 2024-11-20 10:30:39,329 ⚠️  ERROR Uncaught exception main.except_hook:80
nov 20 10:30:39 rubacava ulauncher[3762]: Traceback (most recent call last):
nov 20 10:30:39 rubacava ulauncher[3762]:   File "/usr/lib/python3.12/site-packages/ulauncher/ui/ulauncher_app.py", line 62, in do_activate
nov 20 10:30:39 rubacava ulauncher[3762]:     self.show_launcher()
nov 20 10:30:39 rubacava ulauncher[3762]:   File "/usr/lib/python3.12/site-packages/ulauncher/ui/ulauncher_app.py", line 118, in show_launcher
nov 20 10:30:39 rubacava ulauncher[3762]:     self._window = weakref.ref(UlauncherWindow(application=self))
nov 20 10:30:39 rubacava ulauncher[3762]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nov 20 10:30:39 rubacava ulauncher[3762]:   File "/usr/lib/python3.12/site-packages/ulauncher/ui/windows/ulauncher_window.py", line 31, in __init__
nov 20 10:30:39 rubacava ulauncher[3762]:     super().__init__(
nov 20 10:30:39 rubacava ulauncher[3762]:   File "/usr/lib/python3.12/site-packages/gi/overrides/Gtk.py", line 505, in __init__
nov 20 10:30:39 rubacava ulauncher[3762]:     raise RuntimeError(
nov 20 10:30:39 rubacava ulauncher[3762]: RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.


nov 20 10:32:18 rubacava ulauncher[7132]: cannot open display: :0
nov 20 10:32:18 rubacava systemd[1650]: ulauncher.service: Main process exited, code=exited, status=1/FAILURE
nov 20 10:32:18 rubacava systemd[1650]: ulauncher.service: Failed with result 'exit-code'.
nov 20 10:32:19 rubacava systemd[1650]: ulauncher.service: Scheduled restart job, restart counter is at 3.
nov 20 10:32:19 rubacava systemd[1650]: Starting Ulauncher service...
nov 20 10:32:19 rubacava ulauncher[7239]: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
- [X] I have tried to understand the error message and help myself, before reporting it.
- [X] My issue description has clear steps for how to reproduce the issue.
- [X] This issue applies to the whole Ulauncher application, not for a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by iaacornus** [comment]
hi @friday , i apologize for ping here. Are we currently testing v6 for stable release and on phase of bug fixing, or there are other things to implement? I'm looking to contribute, but not sure what to do, to help fixing bugs or implementing features. I'd appreciate if you can point me to the right direction that will help in releasing v6 stable, cheers for this fantastic work, as always.

**Comment by friday** [comment]
@iaacornus I made several updates like this in the pinned V6 issue, the last one being https://github.com/Ulauncher/Ulauncher/issues/869#issuecomment-2068222245

I am very busy as of late, but I will have time to work on Ulauncher around and after Christmas.

Beta doesn't mean feature freeze. RC/release candidate does, but we're planning to add more functionality besides what's in the milestone. We have been moving things out instead.

One thing I promised very early that would be part of the V6 release is using virtualenv/venv and automatically installing dependencies for extensions. I don't know much about this myself and have tried unsuccessfully to delegate it. So if you could help with that it would be great.

I also would like help with testing Ulauncher with desktop environments without a compositor. Several people reported issues with the shadows.

The main reason I don't want to release it yet is mainly because of the extension API changes not being fully completed, and I don't want to force maintainers to migrate extensions often. This is something that I think I have to finish myself though.

In addition to that I want to have time to update the docs and fully rewrite the website, docs page and extension page.

**Comment by iaacornus** [comment]
> One thing I promised very early that would be part of the V6 release is using virtualenv/venv and automatically installing dependencies for extensions. I don't know much about this myself and have tried unsuccessfully to delegate it. So if you could help with that it would be great.

I'd love to try implementing that. My work uses venv in everyday basis, so I may have a shot in solving it, can't promise tho. But I'll send an mr if ever I managed to implement that.

> I also would like help with testing Ulauncher with desktop environments without a compositor. Several people reported issues with the shadows.

Yes, if that would help, I will spin up some vm with my configs to test it out.

> The main reason I don't want to release it yet is mainly because of the extension API changes not being fully completed, and I don't want to force maintainers to migrate extensions often. This is something that I think I have to finish myself though.

is there anything you need help here? I'll be happy to provide my support and assistance to give back to the project.

Although I can't really help with docs and website since I don't have experience with it, but if you could guide me, I can try. 

Anyway, I'd like to say thank you for your work, along with the contributors to this project, it's a crucial part of my everyday workflow and is a big help. So if there's any help I can offer, you can reach out. I'll also take on these things I've mentioned, maybe you can assign its issue to me if there's one?

**Comment by friday** [comment]
Closing. I think this issue was a temporary GTK or PyGObject issue. I haven't had it happen since this issue was created.
