### ISSUE TITLE
No such interface 'org.freedesktop.Notifications' on object at path /org/freedesktop/Notifications

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#143]
I get the following in .xsession-errors, on Mint 18.2 Cinnamon using Ulauncher 3.0.2r0.

```
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:5: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2
2017-07-27 01:52:07,839 | [1;31mERROR[0m | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 268, in bind_show_app_hotkey
    self.notify_hotkey_change(accel_name)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 273, in notify_hotkey_change
    show_notification("Ulauncher", "Hotkey is set to %s" % display_name)
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py", line 10, in show_notification
    Notify.Notification.new(summary, body, icon).show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.Notifications' on object at path /org/freedesktop/Notifications (19)
```

**Comment by gornostal** [comment]
@CottonEaster are you still seeing this error in Mint?
I installed Min 18.2 Cinamon, but wasn't able to reproduce this issue.

Please reopen if needed

**Comment by CottonEaster** [comment]
Hi. If I run Ulauncher via the terminal, I see, now, only, the following.

```
~ $ ulauncher
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:5: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2
```

So, I think progress has been made, because the warnings are fewer and perhaps - I am not in a position to judge - less serious.

**Comment by gornostal** [comment]
These warnings are expected. Does the app work fine?

**Comment by CottonEaster** [comment]
Yes, the application works as it should, thank you. Still, miminizing log - or even just terminal output - spam (i.e., such stuff as is unnecessary) is a good thing, though some of it might be outside of an application's control.
