### ISSUE TITLE
Crash when launching the program on Ulauncher V6

### ISSUE THREAD

**Issue by witt-bit** [Ulauncher/Ulauncher#1432]
### Environment

Manjaro Linux

### Bug description

![Peek 2024-12-23 22-47](https://github.com/user-attachments/assets/5239a1ee-10f4-4c4f-8bd6-65170bf597ef)

When you click to start the program, the terminal outputs:

```shell
ulauncher                                                                                                                          ✔ 
2024-12-23 22:42:56,919 ⚠️  WARNING 

╔═════════════════════════════════════════════════════════════════════════════╗
║                  YOU ARE RUNNING A PRE-RELEASE of ULAUNCHER.                ║
║ Please do not report extension API support warnings to extension developers ║
║ We are still in the process of developing and documenting these features    ║
╚═════════════════════════════════════════════════════════════════════════════╝

 main.main:60
2024-12-23 22:42:59,037 ⚠️  ERROR Uncaught exception main.except_hook:80
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ulauncher/ui/windows/ulauncher_window.py", line 245, in on_input_key_press
    self.results_nav.activate(self.query, alt=alt)
  File "/usr/lib/python3.12/site-packages/ulauncher/ui/item_navigation.py", line 70, in activate
    events.emit("mode:handle_action", result.on_activation(query, alt))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ulauncher/modes/apps/app_result.py", line 77, in on_activation
    if not launch_app(self._app_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ulauncher/modes/apps/launch_app.py", line 30, in launch_app
    if prefer_raise and app_exec and try_raise_app(app_wm_id):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ulauncher/utils/wm.py", line 46, in try_raise_app
    wm_class = win.get_wm_class()
               ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_wm_class'
```

In addition: This problem occurs after running for a while, and now it occurs every time. I tried to kill the process, but it still crashed

### Log output

```shell
2024-12-23 22:47:27,613 | WARNING | 

╔═════════════════════════════════════════════════════════════════════════════╗
║                  YOU ARE RUNNING A PRE-RELEASE of ULAUNCHER.                ║
║ Please do not report extension API support warnings to extension developers ║
║ We are still in the process of developing and documenting these features    ║
╚═════════════════════════════════════════════════════════════════════════════╝

 | main.main():60
2024-12-23 22:47:32,835 | DEBUG | Screen RGBA visual: <GdkX11.X11Visual object at 0x785ca1a3d280 (GdkX11Visual at 0x5eeaac596830)> | ulauncher_window.__init__():123
2024-12-23 22:47:32,835 | DEBUG | Screen is composited: True | ulauncher_window.__init__():124
2024-12-23 22:47:32,844 | DEBUG | render 0 results | ulauncher_window.show_results():363
2024-12-23 22:47:32,863 | DEBUG | Removing existing socket path /run/user/1000/ulauncher_control | extension_socket_server.start():43
2024-12-23 22:47:33,454 | DEBUG | render 41 results | ulauncher_window.show_results():363
2024-12-23 22:47:33,757 | DEBUG | render 11 results | ulauncher_window.show_results():363
2024-12-23 22:47:34,209 | ERROR | Uncaught exception | main.except_hook():80
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ulauncher/ui/windows/ulauncher_window.py", line 245, in on_input_key_press
    self.results_nav.activate(self.query, alt=alt)
  File "/usr/lib/python3.12/site-packages/ulauncher/ui/item_navigation.py", line 70, in activate
    events.emit("mode:handle_action", result.on_activation(query, alt))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ulauncher/modes/apps/app_result.py", line 77, in on_activation
    if not launch_app(self._app_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ulauncher/modes/apps/launch_app.py", line 30, in launch_app
    if prefer_raise and app_exec and try_raise_app(app_wm_id):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ulauncher/utils/wm.py", line 46, in try_raise_app
    wm_class = win.get_wm_class()
               ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_wm_class'
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
- [X] I have tried to understand the error message and help myself, before reporting it.
- [X] My issue description has clear steps for how to reproduce the issue.
- [X] This issue applies to the whole Ulauncher application, not for a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
So restarting Ulauncher doesn't work? You have to restart the whole system? Or does that also not work?

**Comment by friday** [comment]
I just realized this could be my fault for removing python-xlib as a dependency just now. We got rid of that, but then we re-introduced it as a sub-dependency of a small wrapper library that we ended up vendoring because it's not widely available in systems packages.

**Comment by friday** [comment]
I'm travelling so I can't fix it right now, but you can install it separately and maybe it'll work.

**Comment by friday** [comment]
Fixed ^ Although when I tested without python-xlib the fallback worked fine.

**Comment by friday** [comment]
Main problem should be fixed now too, as in no crash. Although I was never able to replicate it, and your system may not support this feature for all or some app.
![image](https://github.com/user-attachments/assets/f6f897d9-a5e6-4bb7-8197-25759ad33589)

Could you grab the log output when you run with this? Will it print "Skipping empty client list stacking result" a lot of times or just one?

**Comment by witt-bit** [comment]
> Main problem should be fixed now too, as in no crash. Although I was never able to replicate it, and your system may not support this feature for all or some app.主要问题现在也应该得到解决，因为不会发生崩溃。尽管我永远无法复制它，并且您的系统可能不支持所有或某些应用程序的此功能。 ![image](https://private-user-images.githubusercontent.com/515120/398258548-f6f897d9-a5e6-4bb7-8197-25759ad33589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMDQ4NzUsIm5iZiI6MTczNTAwNDU3NSwicGF0aCI6Ii81MTUxMjAvMzk4MjU4NTQ4LWY2Zjg5N2Q5LWE1ZTYtNGJiNy04MTk3LTI1NzU5YWQzMzU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwMTQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTBhNjJlMzNiMzM1MzQxY2E4ZWYxZDdkYmMyMGU5MTRkYjVhMjZjOTU0ZmY3NjNkNGI5ZThkMTNlYTA0NzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w59Up7EttJbGYG7EhHwVZWziGs_al1pyvCWmU6ugyCc)
> 
> Could you grab the log output when you run with this? Will it print "Skipping empty client list stacking result" a lot of times or just one?当你运行这个时，你能抓取日志输出吗？它会多次打印“跳过空客户端列表堆叠结果”还是只打印一次？


I suspect it is indeed a dependency issue. I have two identical computers with the same operating system. One is installed with `ulauncher-dev-bin` and the other is installed with `ulauncher-git`. The above errors are normal when installing ulauncher-dev-bin, and the option 'Switch to application if it's already running' is also normal.

`ulauncher-dev-bin PKGBUILD`
```shell
# Maintainer: witt <1989161762 at qq dot com>

# To install, run `makepkg -si`

pkgname=ulauncher-dev-bin
pkgver=6.0.0-beta17
pkgrel=1
pkgdesc='Feature rich application Launcher for Linux.'
arch=('any')
url="https://ulauncher.io"
license=('GPL3')
depends=('gobject-introspection-runtime' 'libkeybinder3' 'gtk3' 'webkit2gtk' 'libnotify'
         'gdk-pixbuf2' 'wmctrl' 'python-dbus' 'python-levenshtein' 'python-pyinotify'
         'python-websocket-client' 'python-pyxdg' 'python-gobject' 'python-cairo')
makedepends=('git' 'python-setuptools')
optdepends=('libappindicator-gtk3: tray icon')
install="ulauncher.install"
provides=('ulauncher' 'ulauncher-bin' 'ulauncher-dev' ' ')
conflicts=('ulauncher' 'ulauncher-git' 'ulauncher-bin' 'ulauncher-appimage')
source=(
    "https://github.com/Ulauncher/Ulauncher/releases/download/v${pkgver}/ulauncher-${pkgver}.tar.gz"
)
sha256sums=('b4e05f4b78c34c6d552371efed2262195dfcba79f6ade1ca8ba4d47e16fd368a')

build() {
  cd ulauncher
  env PATH="$(getconf PATH)" python setup.py build > /dev/null
}

# 修复不能出现短线的问题
fixver(){
  pkgver="${pkgver//[:\/\- ]/}";
}


package() {
  cd ulauncher
  export PYTHONHASHSEED=0
  env PATH="$(getconf PATH)" python setup.py install --root="${pkgdir}" --optimize=1 --skip-build > /dev/null
  rm -rf "$pkgdir"/usr/share/ulauncher/preferences/{no*,src,bow*,gul*,pack*}
  find "${pkgdir}" -type d -name __pycache__ -exec rm -rf \;
}

fixver;

```

**Comment by friday** [comment]
> I suspect it is indeed a dependency issue. I have two identical computers with the same operating system. One is installed with `ulauncher-dev-bin` and the other is installed with `ulauncher-git`. The above errors are normal when installing ulauncher-dev-bin, and the option 'Switch to application if it's already running' is also normal.

No. Your package has the outdated v5 dependencies. None of the extra packages in your package is used in Ulauncher, nor has anything to do with the logic that is failing.

**Comment by friday** [comment]
This fixed in December ^
