### ISSUE TITLE
Unable to save preferences if ULauncher is running and "Show Indicator Icon" button has been checked

### ISSUE THREAD

**Issue by returnnihil** [Ulauncher/Ulauncher#173]
**Steps to reproduce:**
1. Open ULauncher
2. Open Settings menu
3. Verify "Show Indicator Icon" is checked and the notification appears in the notification area
4. Change any preference
5. Exit the window

Your preference will be valid until you restart ULauncher, so it's like it's recognizing the change somewhere, but your preference modification does not saved to the `settings.json` file.

If you uncheck the "Show Indicator Icon" box and then change whatever preferences, then your settings will save correctly.

**Ulauncher version**: 3.2.1.r1
**Linux distro**: Antergos (4.13.5-1-ARCH)
**Desktop environment**: Openbox (3.6.1) w/ Tint2 panel (15.2)

**Logs**:
```2017-10-15 16:02:33,828 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", 
line 260, in bind_show_app_hotkey
    self.notify_hotkey_change(accel_name)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", 
line 267, in notify_hotkey_change
    show_notification("Ulauncher", "Hotkey is set to %s" % display_name)
  File "/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py", 
line 10, in show_notification
    Notify.Notification.new(summary, body, icon).show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: 
The name org.freedesktop.Notifications was not provided by any .service files (2)
```

**Comment by gornostal** [comment]
Try installing `notification-daemon`
If that helps, I'll add it to the dependencies
Normally it's installed with a DE.

**Comment by gornostal** [comment]
Closing due to no response. Please reopen if needed

**Comment by nvick** [comment]
I'm having a similar issue. Deselecting "Show Indicator Icon" does not fix the issue. 

**Ulauncher version**: 4.1.0.r1
**Linux distro**: Ubuntu 18.04
**Desktop environment**: bspwm

When I start up I see the following in my log.
```bash
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.                                                                                                                                                             from gi.repository import Notify                                                                                                                                                                                 
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.                                                                                                                                                                       from gi.repository import Gio, Gtk, WebKit2, GLib                                                                                                                                                                
2018-07-27 07:58:54,898 | ERROR | ulauncher: except_hook() | Uncaught exception                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 277, in bind_show_app_hotkey                                                                                               
    self.notify_hotkey_change(accel_name)                                                                                                                                                                          
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 284, in notify_hotkey_change                                                                                               
    show_notification("Ulauncher", "Hotkey is set to %s" % display_name)                                                                                                                                           
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py", line 10, in show_notification                                                                                                        Notify.Notification.new(summary, body, icon).show()                                                                                                                                                            Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2) 
```
When I update my hot keys:
```bash
file:///usr/share/ulauncher/preferences/dist/static/js/app.883257bafcc42645416b.js:12484:15: CONSOLE INFO onNotification hotkey-show-app {"displayValue":"Ctrl+Alt+Space","value":"<Primary><Alt>space"}           
2018-07-27 08:01:22,844 | ERROR | ulauncher: except_hook() | Uncaught exception                                                                                                                                    Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 240, in prefs_set_hotkey_show_app                                                                               
    ulauncher_window.bind_show_app_hotkey(hotkey)                                                                                                                                                                  
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 277, in bind_show_app_hotkey                                                                                               
    self.notify_hotkey_change(accel_name)                                                                                                                                                                          
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 284, in notify_hotkey_change                                                                                                   show_notification("Ulauncher", "Hotkey is set to %s" % display_name)                                                                                                                                           
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py", line 10, in show_notification                                                                                                    
    Notify.Notification.new(summary, body, icon).show()                                                                                                                                                            Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2) 
```

**Comment by gornostal** [comment]
Hi @nvick 
Please check out these comments:
https://github.com/HenriWahl/Nagstamon/issues/357#issuecomment-275418229
https://stackoverflow.com/a/35893354/805664

Hope that helps

**Comment by nvick** [comment]
Thanks, I’ll give it a go.
