### ISSUE TITLE
Update or Add extension Unexpected API error. InvalidGithubUrlError: 

### ISSUE THREAD

**Issue by ghost** [Ulauncher/Ulauncher#192]
**Steps to reproduce:**
Try to add or Update an extension

**Ulauncher version**:
3.2.1.r1

**Linux distro**:
Arch Rolling

**Desktop environment**:
KDE Plasma 5

**Logs**
https://gist.github.com/MBuchaus/46f26c1be33e7f086c47cb63ba953249#file-ulauncher-api

**Comment by gornostal** [comment]
What extension are you trying to update?

**Comment by MBuchaus** [comment]
I get this same error updating any of the preinstalled extensions or adding any from the extension page from the .io site..  I did get them installed a few days ago   update check and all worked for a bit   then it went back to the same behavior.  I need to dig into it more    cause that sounds like it could be networking  but I've seen no other problems hitting git hub etc..    strange....

**Comment by gornostal** [comment]
I've verified that extension install/update works on v3.2.1.r1
It really looks like something with your system.
I'm closing this issue.

**Comment by MBuchaus** [comment]
Could I be missing a library?  ARCH is python 3 based  but ulauncher is python2

2018-01-14 18:26:31,233 | ERROR | ulauncher.api.server.ExtensionDownloader: get_new_version() | gh_ext.get_ext_meta() failed. HTTPError: 
2018-01-14 18:26:31,233 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. InvalidGithubUrlError: Project is not available on Github
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 148, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/site-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 367, in prefs_extension_check_updates
    return ExtensionDownloader.get_instance().get_new_version(ext_id)
  File "/usr/lib/python2.7/site-packages/ulauncher/api/server/ExtensionDownloader.py", line 139, in get_new_version
    raise InvalidGithubUrlError('Project is not available on Github')
InvalidGithubUrlError: Project is not available on Github

**Comment by gornostal** [comment]
Ulauncher has python2 in its dependencies.

Try this:
Open Python2 REPL by running this command in terminal: `python2`
Please run it from the user you run Ulauncher.

Then run the following code in the REPL:

```
import json
from urllib2 import urlopen
branch_head_url = 'https://api.github.com/repos/ulauncher/ulauncher-timer/git/refs/heads/master'
branch_head = json.load(urlopen(branch_head_url))
branch_head_commit = json.load(urlopen(branch_head['object']['url']))
```

This is where the error occurs. If it works, then the bug is in Ulauncher somewhere.

**Comment by MBuchaus** [comment]
I'm getting a forbidden response from the urllib

>>> import json
>>> from urllib2 import urlopen
>>> branch_head_url = 'https://api.github.com/repos/ulauncher/ulauncher-timer/git/refs/heads/master'
>>> branch_head = json.load(urlopen(branch_head_url))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by gornostal** [comment]
Interesting.
Do you have a firewall?

**Comment by MBuchaus** [comment]
Yes but 
sudo iptables -nvL
Chain INPUT (policy ACCEPT 203 packets, 245K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 44 packets, 40412 bytes)
 pkts bytes target     prot opt in     out     source               destination         
Archovo [~]── -

**Comment by gornostal** [comment]
yeah, it definitely passes the firewall because you get HTTP response back with status 403

**Comment by gornostal** [comment]
did you try to open that URL in a browser?

**Comment by MBuchaus** [comment]
"message": "API rate limit exceeded for 64.53.153.18. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"

**Comment by MBuchaus** [comment]
and yep that's my ip

**Comment by MBuchaus** [comment]
hmm  auth via the python urllib?

**Comment by gornostal** [comment]
Looks like something on your PC made lot's of API requests to github
I don't think that could be Ulauncher. Maybe something else?

**Comment by gornostal** [comment]
> hmm auth via the python urllib?
It should work without auth.

**Comment by gornostal** [comment]
> 64.53.153.18

This can be not ONLY your IP.

Try using VPN maybe?

**Comment by MBuchaus** [comment]
Most likely emacs Paradox (package-system) but I use and API key for that

it's the external Ip of my cable modem. yeah it's me..  I have services on dynamic dns comming in on it too

**Comment by MBuchaus** [comment]
trying the vpn

**Comment by MBuchaus** [comment]
Yeah using a differnt IP is allowing all the access..  I'll have to find out what service is banging on github.    thanks Gornostal  for the troubleshooting help

**Comment by gornostal** [comment]
no problem

**Comment by pietje76** [comment]
i have the same issue here. trying to install 25 extensions and it stops somewhere at 10. after that, i have the same error message. i'll try another ip. can ulauncher bypass this setting from github?

**Comment by friday** [comment]
@pietje76 @gornostal:

This happens if there's a trailing slash in the URL (which are valid github URLs which doesn't redirect back to the same URL without the slash).

Ex:
Works: `https://github.com/Ulauncher/ulauncher-kill`
Doesn't work: `https://github.com/Ulauncher/ulauncher-kill/`

The issue should be reopened imo.

**Comment by zeue** [comment]
@gornostal 

this should be reopened, or at least revisited in another issue, as the problem still persists today as the github api limits requests from a given IP if you try to add a lot of extensions at one time (such as a reinstall)

perhaps we could add an optional field in the settings to allow users to input a github access token to pass the authentication checks? as authenticated requests have a much higher threshold for the rate limiting

**Comment by lalitmee** [comment]
I got this error while installing any extension.

Message: HTTP Error 403: Forbidden
Error Name: UnhandledError
Type: HTTPError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 400, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 80, in find_compatible_version
    return self.get_commit(sha_or_branch)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 89, in get_commit
    resp = json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

**Comment by friday** [comment]
That's a different error @lalitmee Could you please create a new issue for it? I'm not sure it's an issue with Ulauncher, a legit network issue or local config issue, but at least it could be handled better.

**Comment by friday** [comment]
Closing in favor of #807 and #609 (and #423 has more info too)
