### ISSUE TITLE
ulauncher exception on Wayland Gnome

### ISSUE THREAD

**Issue by PierfrancescoArdino** [Ulauncher/Ulauncher#203]
**Steps to reproduce:**
Run GDK_BACKEND=x11 ulauncher from command line

**Ulauncher version**: ulauncher-git
**Linux distro**: Arch Linux
**Desktop environment**: Gnome on Wayland

**Logs**:

```
GDK_BACKEND=x11 ulauncher
/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 25, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/ulauncher/main.py", line 101, in main
    toggle_window()
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method' % method_name)
UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: toggle_window is not a valid method
```

**Comment by PierfrancescoArdino** [comment]
Ulauncher works when set as startup application, the problem exists only when launched from CLI

**Comment by gornostal** [comment]
That's weird.
It looks as if you're already running an old version of the app, while trying to run `GDK_BACKEND=x11 ulauncher` from CLI. Could that be the case?

**Comment by PierfrancescoArdino** [comment]
Well, I don't think so. I mean, I've removed the older version of the app before installing the newer one

**Comment by gornostal** [comment]
```
  File "/usr/lib/python2.7/site-packages/ulauncher/main.py", line 101, in main
    toggle_window()
```
This line is executed _only if_ Ulauncher is already running.
Could you check `ps` and if it's running, stop that instance?

**Comment by PierfrancescoArdino** [comment]
Mmm yeah, you're right, probably I forgot to kill the process of the older instance even if I've removed it. Now it works without any problems, still I've some problems with the position of the launcher in the screen, but I will open another issue.

**Comment by gornostal** [comment]
OK. Sure
