### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [Ulauncher/Ulauncher#235]
**Steps to reproduce:**
 python2 setup.py build

**Linux distro**: Arch
**Desktop environment**: LXQt

```
=> Starting build()...
Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    cmdclass={'install': InstallAndUpdateDataDirectory}
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 412, in __add_imports
    elif node.module and __external_mod(cur_module, node.module, attrs):
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 354, in __external_mod
    mod = __import__(cur_module + '.' + module)
  File "/home/solaraquarion/build/ulauncher-git/src/ulauncher/ulauncher/search/apps/AppDb.py", line 8, in <module>
    from ulauncher.util.image_loader import get_app_icon_pixbuf
  File "/home/solaraquarion/build/ulauncher-git/src/ulauncher/ulauncher/util/image_loader.py", line 3, in <module>
    from gi.repository import Gtk, Gio, GLib, GdkPixbuf
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/overrides/Gdk.py", line 165, in <module>
    class Window(Gdk.Window):
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 138, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gdk' object has no attribute 'Window'
==> ERROR: A failure occurred in build().


```

**Comment by gornostal** [comment]
Hi,
If you are trying to build for Arch, please use PKGBUILD from [ulauncher-git on AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ulauncher-git)

I've never tried running `python2 setup.py build` nor I know what the end result of that should be. Sorry.

**Comment by SolarAquarion** [comment]
Even "python2 setup.py" doesn't work

**Comment by SolarAquarion** [comment]
python2 setup.py       
Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    cmdclass={'install': InstallAndUpdateDataDirectory}
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 412, in __add_imports
    elif node.module and __external_mod(cur_module, node.module, attrs):
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 354, in __external_mod
    mod = __import__(cur_module + '.' + module)
  File "/home/solaraquarion/build/ulauncher-git/src/ulauncher/ulauncher/search/apps/AppDb.py", line 8, in <module>
    from ulauncher.util.image_loader import get_app_icon_pixbuf
  File "/home/solaraquarion/build/ulauncher-git/src/ulauncher/ulauncher/util/image_loader.py", line 3, in <module>
    from gi.repository import Gtk, Gio, GLib, GdkPixbuf
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/overrides/Gdk.py", line 165, in <module>
    class Window(Gdk.Window):
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 138, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gdk' object has no attribute 'Window'

**Comment by gornostal** [comment]
Could you make sure you have gtk3 package installed?

Since you are running LXQt DE, you may not have GTK3.
I guess I should have that as an explicit dependency in PKGBUILD file.

**Comment by SolarAquarion** [comment]
I have GTK3 properly installed

local/gtk3-ubuntu 3.22.28+74+gcc967849f7-2
    GObject-based multi-platform toolkit

**Comment by gornostal** [comment]
Hmm... It definitely looks like a dependency issue. I don't know that else can it be.

**Comment by SolarAquarion** [comment]
raceback (most recent call last):
  File "setup.py", line 150, in <module>
    cmdclass={'install': InstallAndUpdateDataDirectory}
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 98,
in setup
    __requires(attrs, src_all)
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 471,
in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 412,
in __add_imports
    elif node.module and __external_mod(cur_module, node.module, attrs):
  File "/usr/lib/python2.7/site-packages/DistUtilsExtra/auto.py", line 354,
in __external_mod
    mod = __import__(cur_module + '.' + module)
  File
"/home/solaraquarion/build/ulauncher-git/src/ulauncher/ulauncher/search/apps/AppDb.py",
line 8, in <module>
    from ulauncher.util.image_loader import get_app_icon_pixbuf
  File
"/home/solaraquarion/build/ulauncher-git/src/ulauncher/ulauncher/util/image_loader.py",
line 3, in <module>
    from gi.repository import Gtk, Gio, GLib, GdkPixbuf
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in
load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in
load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 146, in
load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line
125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/gi/overrides/Gdk.py", line 165, in
<module>
    class Window(Gdk.Window):
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 138, in
__getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gdk' object has no attribute 'Window'

There's something in the code that features "Window"

**Comment by gornostal** [comment]
Why I think it's a dependency problem is because Gdk object should have Window attribute (that's what the message says).
In your case it doesn't have that. So I assumed GTK+ library was installed incorrectly or something.
