### ISSUE TITLE
ProjectPathNotFoundError on startup

### ISSUE THREAD

**Issue by BartWillems** [Ulauncher/Ulauncher#272]
I've installed Ulauncher through the AUR and is crashes on startup.
I've already installed the python2-notify package.

**Steps to reproduce:**
Start Ulauncher

**Ulauncher version**:
Ulauncher version 4.1.0.r1
**Linux distro**:
Arch Linux
**Desktop environment**:
KDE 5.13

**Logs**:

<https://gist.github.com/BartWillems/4c1dfbc182592e3cfbfb6ad04f038d74>

**Comment by BartWillems** [comment]
For some reason, I can't reproduce it with the newest version. I also had some python updates, so maybe one of them was bugged?

**Comment by friday** [comment]
I can reproduce this in Arch using yay to install:
```sh
yay -Syu --noconfirm ulauncher
ulauncher -v
```

It does not happen if installing with pamac (gui installer) or the official instructions
(`git clone https://aur.archlinux.org/ulauncher.git && cd ulauncher && makepkg -is`).

This "fixes" it for me (discovered while trying to debug). I have no idea why:
`sudo touch /usr/lib/python2.7/site-packages/ulauncher/config.py`

Full log:
```
2018-09-11 17:28:04,690 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 25, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/ulauncher/main.py", line 120, in main
    window = UlauncherWindow.get_instance()
  File "/usr/lib/python2.7/site-packages/ulauncher/util/decorator/singleton.py", line 16, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 52, in get_instance
    return cls()
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 60, in __new__
    builder = Builder.new_from_file('UlauncherWindow')
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/Builder.py", line 43, in new_from_file
    ui_filename = get_data_file('ui', '%s.ui' % (builder_file_name,))
  File "/usr/lib/python2.7/site-packages/ulauncher/config.py", line 40, in get_data_file
    return os.path.join(get_data_path(), *path_segments)
  File "/usr/lib/python2.7/site-packages/ulauncher/config.py", line 57, in get_data_path
    raise ProjectPathNotFoundError(abs_data_path)
ProjectPathNotFoundError: /usr/lib/python2.7/site-packages/data
```

**Comment by noam09** [comment]
Same here, happened with the previous upgrades as well. "Manual" install (below) works, but via `yay` does not. 
```
git clone https://aur.archlinux.org/ulauncher.git && cd ulauncher && makepkg -is
```

**Comment by gornostal** [comment]
> I can reproduce this in Arch using yay to install:

Finally we know steps to reproduce :)
Thanks @friday, @noam09 

I'm going to see if I can find a workaround that doesn't require an extra step for a user

**Comment by gornostal** [comment]
It's fixed now. Turns out python cache files were not removed with yay install
