### ISSUE TITLE
Encoding error when entering an accented search query after a keyword extension

### ISSUE THREAD

**Issue by nicolasm** [Ulauncher/Ulauncher#294]
Hi,

**Steps to reproduce:**
Type fh exposé
Please note that it happens with all extensions, not just Firefox History.

**Ulauncher version**: 4.1.1.r1-1
**Linux distro**: Arch Linux
**Desktop environment**: KDE Plasma

**Logs**:

com.github.rmassidda.ulauncher-firefox-history | 2018-09-23 20:15:06,298 | DEBUG | ulauncher.api.client.Client: send() | Send message
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/util/SimpleWebSocketServer.py", line 577, in _parseMessage
    self._handlePacket()
  File "/usr/lib/python2.7/site-packages/ulauncher/util/SimpleWebSocketServer.py", line 239, in _handlePacket
    raise Exception('invalid utf-8 payload')
Exception: invalid utf-8 payload
2018-09-23 20:15:06,458 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results

Best regards,
Nicolas

**Comment by friday** [comment]
4.3.0.r2-1 is the latest AUR release (since yesterday). May not solve the issue but always good to use the latest version when reporting.

**Comment by nicolasm** [comment]
I just upgraded but the issue is still there.

**Comment by gornostal** [comment]
Fixed in 4.3.1.r4
