### ISSUE TITLE
Hotkey is not persistent (CentOS / xfce)

### ISSUE THREAD

**Issue by ababak** [Ulauncher/Ulauncher#365]
### Steps to reproduce
1. Set a hotkey
2. Quit ULauncher
3. Launch ULauncher and check settings

### Current behavior
1. A hotkey is set, works fine
2. Ulauncher Quit
3. Settings revert to Ctrl+Space, `~/.config/ulauncher/settings.json` is not changed

### Expected behavior
Hotkey saved

### Environment
**Ulauncher version**:
**CentOS Linux 7 (Core)**:
**xfce**:

### Logs
```
/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
2019-04-08 10:10:44,249 | INFO | ulauncher: main() | Ulauncher version 4.3.1.r4
2019-04-08 10:10:44,249 | INFO | ulauncher: main() | GTK+ 3.22.30
2019-04-08 10:10:44,250 | INFO | ulauncher: main() | Is Wayland: False
2019-04-08 10:10:44,250 | INFO | ulauncher: main() | Wayland compatibility: off
2019-04-08 10:10:44,286 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2019-04-08 10:10:44,293 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2019-04-08 10:10:44,294 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2019-04-08 10:10:44,294 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2019-04-08 10:10:44,296 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2019-04-08 10:10:44,297 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2019-04-08 10:10:44,297 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2019-04-08 10:10:44,297 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2019-04-08 10:10:44,298 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2019-04-08 10:10:44,298 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2019-04-08 10:10:44,301 | DEBUG | ulauncher.util.display: get_screens() | Found 2 monitor(s).
2019-04-08 10:10:44,302 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 4096, H: 2160
2019-04-08 10:10:44,302 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 1 - X: 4096, Y: 720, W: 2560, H: 1440
2019-04-08 10:10:44,314 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2019-04-08 10:10:44,321 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2019-04-08 10:10:44,322 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2019-04-08 10:10:44,344 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-text-expander" started. PID 19917
2019-04-08 10:10:44,347 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ababak.ulauncher-slashes" started. PID 19919
2019-04-08 10:10:44,387 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2019-04-08 10:10:44,407 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 277, in bind_show_app_hotkey
    self.notify_hotkey_change(accel_name)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 284, in notify_hotkey_change
    show_notification("Ulauncher", "Hotkey is set to %s" % display_name)
  File "/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py", line 10, in show_notification
    Notify.Notification.new(summary, body, icon).show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
/usr/lib/python2.7/site-packages/ulauncher/util/image_loader.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio, GLib, GdkPixbuf

(ulauncher:19900): Gdk-CRITICAL **: 10:10:44.522: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2019-04-08 10:10:44,577 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.brpaz.ulauncher-text-expander" connected
2019-04-08 10:10:44,578 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.brpaz.ulauncher-text-expander"
2019-04-08 10:10:44,580 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.ababak.ulauncher-slashes" connected
2019-04-08 10:10:44,581 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.ababak.ulauncher-slashes"
com.github.brpaz.ulauncher-text-expander | 2019-04-08 10:10:44,581 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
com.github.ababak.ulauncher-slashes | 2019-04-08 10:10:44,582 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2019-04-08 10:10:45,185 | INFO | ulauncher.util.image_loader: get_app_icon_pixbuf() | Could not load icon for nepomuk. E: gtk-icon-theme-error-quark: Icon 'nepomuk' not present in theme gnome (0)
2019-04-08 10:10:45,186 | INFO | ulauncher.util.image_loader: get_app_icon_pixbuf() | Could not load icon for nepomuk. E: gtk-icon-theme-error-quark: Icon 'nepomuk' not present in theme gnome (0)
2019-04-08 10:10:45,187 | INFO | ulauncher.util.image_loader: get_app_icon_pixbuf() | Could not load icon for nepomuk. E: gtk-icon-theme-error-quark: Icon 'nepomuk' not present in theme gnome (0)
2019-04-08 10:10:45,188 | INFO | ulauncher.util.desktop.reader: find_apps_cached() | Found 132 apps in cache
2019-04-08 10:10:45,193 | INFO | ulauncher.util.desktop.reader: read_desktop_file() | Could not read "/home/babak/.local/share/applications/userapp-rv-Z18F7Y.desktop": constructor returned NULL
2019-04-08 10:10:45,193 | INFO | ulauncher.util.desktop.reader: read_desktop_file() | Could not read "/home/babak/.local/share/applications/rv.desktop": constructor returned NULL
2019-04-08 10:10:45,208 | INFO | ulauncher.util.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/evolution-calendar.desktop": constructor returned NULL
2019-04-08 10:10:45,225 | INFO | ulauncher.util.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/Autodesk-Maya2016.desktop": constructor returned NULL
2019-04-08 10:10:45,228 | INFO | ulauncher.util.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/kde4/knetattach.desktop": constructor returned NULL
2019-04-08 10:10:45,245 | INFO | ulauncher.util.image_loader: get_app_icon_pixbuf() | Could not load icon for nepomuk. E: gtk-icon-theme-error-quark: Icon 'nepomuk' not present in theme gnome (0)
2019-04-08 10:10:45,245 | INFO | ulauncher.util.image_loader: get_app_icon_pixbuf() | Could not load icon for nepomuk. E: gtk-icon-theme-error-quark: Icon 'nepomuk' not present in theme gnome (0)
2019-04-08 10:10:45,246 | INFO | ulauncher.util.image_loader: get_app_icon_pixbuf() | Could not load icon for nepomuk. E: gtk-icon-theme-error-quark: Icon 'nepomuk' not present in theme gnome (0)
2019-04-08 10:10:45,247 | INFO | ulauncher.util.desktop.reader: find_apps_cached() | Found 132 apps in the system
2019-04-08 10:10:45,247 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.93 seconds
2019-04-08 10:10:45,264 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2019-04-08 10:10:49,016 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2019-04-08 10:10:49,034 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2019-04-08 10:10:49,035 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2019-04-08 10:10:49,157 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2019-04-08 10:10:49,158 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2019-04-08 10:10:49,165 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2019-04-08 10:10:49,167 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
Gtk-Message: 10:10:49.173: GtkDialog mapped without a transient parent. This is discouraged.
2019-04-08 10:10:49,515 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2019-04-08 10:10:50,945 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_showhotkey_dialog() | Show hotkey-dialog for hotkey-show-app
Gtk-Message: 10:10:50.954: GtkDialog mapped without a transient parent. This is discouraged.
file:///usr/share/ulauncher/preferences/dist/static/js/app.167a9abab36a4d9cdc72.js:12484:15: CONSOLE INFO onNotification hotkey-show-app {"displayValue":"Next Group","value":"ISO_Next_Group"}
2019-04-08 10:10:53,297 | DEBUG | ulauncher: on_hotkey_input_key_press_event() | Invalid hotkey 'Return', ('Return') is not allowed
2019-04-08 10:10:53,316 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_set_hotkey_show_app() | Set hotkey-show-app to ISO_Next_Group
2019-04-08 10:10:53,317 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: ISO_Next_Group
2019-04-08 10:10:53,324 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 240, in prefs_set_hotkey_show_app
    ulauncher_window.bind_show_app_hotkey(hotkey)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 277, in bind_show_app_hotkey
    self.notify_hotkey_change(accel_name)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 284, in notify_hotkey_change
    show_notification("Ulauncher", "Hotkey is set to %s" % display_name)
  File "/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py", line 10, in show_notification
    Notify.Notification.new(summary, body, icon).show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)


```

**Comment by friday** [comment]
What did you try to set it to? Judging by the log it seems to think you set it to Enter (Return) "`Invalid hotkey 'Return', ('Return') is not allowed`", which would indeed cause this behavior.

**Comment by ababak** [comment]
I tried "Cmd-Space" (it does work as a hotkey), Cmd-1, Ctrl-1 with the same results. All of them do work but no shortcut is being saved.

**Comment by friday** [comment]
It's probably because Gnome already uses it for switching keyboard, and the super key hijacks focus anyway.

You can set to that combo if you unset the gnome defaults first.

```
gsettings set org.gnome.mutter overlay-key ''
gsettings set org.gnome.desktop.wm.keybindings switch-input-source '[]'
``````

**Comment by ababak** [comment]
I might be wrong but it looks like the problem is how ULauncher saves the config. The hotkeys do work after I set them until quit. The same thing happens with "Ctrl-1" which is not assigned to anything else.

**Comment by ababak** [comment]
Even it looks like it crashes when posting a notification on my system which prevents it from saving the config file.

**Comment by friday** [comment]
I can't reproduce that. Maybe it's related to this: https://bbs.archlinux.org/viewtopic.php?id=202812

**Comment by ababak** [comment]
The fix was pretty simple, I didn't have a notification daemon installed:
`sudo yum install xfce4-notifyd`

Probably, not a bad idea would be to catch these errors? Here's a short Python session showing an error:

```python
Python 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Notify', '0.7')
>>> from gi.repository import Notify
>>> Notify.init('ulauncher')
True
>>> Notify.Notification.new('summary', 'body').show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```
after installing:
```python
>>> Notify.Notification.new('summary', 'body').show()
True
```


Thank you!

**Comment by friday** [comment]
> Probably, not a bad idea would be to catch these errors?

It's not my call, but I agree 👍

**Comment by friday** [comment]
It's in the v6 branch now (see commit above). Follow https://github.com/Ulauncher/Ulauncher/issues/869 if you want to be notified of v6 release plans, but it's not like this was holding you back.
