### ISSUE TITLE
Unexpected API error. KeyError: api_version

### ISSUE THREAD

**Issue by RomanDanyk** [Ulauncher/Ulauncher#399]
I can't add extension [ulauncher-remmina](https://github.com/noam09/ulauncher-remmina).

### Steps to reproduce
1. Open Ulauncher preferences
2. Go to Extensions tab
2. Run Add extention wizard
3. Enter extention URL - https://github.com/noam09/ulauncher-remmina

### Current behavior
There is error message "Unexpected API error. KeyError: api_version"

### Expected behavior
Added extension [ulauncher-remmina](https://github.com/noam09/ulauncher-remmina)

### Environment
**Ulauncher version**: v4.1.0.r1
**Linux distro**: Ubuntu 18.04.2 LTS
**Desktop environment**: Gnome 3.28.2

### Logs
```
2019-06-19 09:15:55,099 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://github.com/noam09/ulauncher-remmina
2019-06-19 09:15:57,864 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: api_version
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 356, in prefs_extension_add
    ExtensionRunner.get_instance().run(ext_id)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionRunner.py", line 52, in run
    manifest.check_compatibility()
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 90, in check_compatibility
    if self.get_api_version() != '1':
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 43, in get_api_version
    return self.manifest['api_version']
KeyError: 'api_version'
```

**Comment by friday** [comment]
This is almost certainly a duplicate of #273. That extension requires [remmina](https://remmina.org/) to be installed and this error is what happens otherwise.

Misleading/confusing that it happens during install though. Should be handled better.

**Comment by RomanDanyk** [comment]
I have installed Remmina version 1.3.4.
I've upgraded Ulancher to v5.3.0~beta1. And after that, I managed to install extension ulauncher-remmina.
