### ISSUE TITLE
App results not showing up

### ISSUE THREAD

**Issue by wojciechrak** [Ulauncher/Ulauncher#412]
# Steps to reproduce
1. Open ULauncher
2. Start typing

### Current behavior
No results are shown.
Exception in logs

### Expected behavior
Results are displayed

### Environment
**Ulauncher version**: 4.4.0.r1
**Linux distro**: Xubuntu 18.04
**Desktop environment**: Xfce

### Logs
https://gist.github.com/wojciechrak/552bcbf814919f50e98b25be7afbc114

**Comment by gornostal** [comment]
Hi @wojciechrak 

When you opened this issue you have probably seen a template for a bug report.
Could you update the description using that template please?

**Comment by wojciechrak** [comment]
Hi @gornostal, perhaps bug report template was added after my post, since I don't recall seeing this when reporting. Anyway, I've updated this issue according to template

**Comment by digitaltopo** [comment]
I have a similar issue where no results show up, but the error message is different.
Looks like a text encoding error?:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte
2019-08-22 23:25:19,292 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 161, in on_input_changed
    Search.get_instance().on_query_change(self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 40, in on_query_change
    self._choose_search_mode(query).handle_query(query).run()
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppSearchMode.py", line 22, in handle_query
    result_list = self.app_db.find(query)
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppDb.py", line 156, in find
    result_list.append(AppResultItem(rec))
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppResultItem.py", line 16, in __init__
    self._app_stat_db = AppStatDb.get_instance()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppStatDb.py", line 18, in get_instance
    return cls(os.path.join(CACHE_DIR, 'app_stat_db.db')).open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 35, in open
    self.set_records(pickle.load(_in))
```

**Comment by gornostal** [comment]
@wojciechrak, @digitaltopo try deleting `~/.cache/ulauncher-cache/*db`

I'm not exactly sure how to reliably reproduce the issue, but it occurs because the search DB files were created with a different version of Python

Please reopen if that doesn't help

**Comment by wojciechrak** [comment]
Thanks @gornostal, clearing cache did the trick.
I wish this was written somewhere in the FAQ or wherever.

And actually, the path was slightly different: `~/.cache/ulauncher_cache/*db` (underscore `_` instead of hyphen `-`)

**Comment by gornostal** [comment]
Thanks. I've edited my comment.

**Comment by mannyy2020** [comment]
Hi @gornostal I am having a similar issue when typing into the search bar no results are appearing. Any solutions ?

[last.log](https://github.com/Ulauncher/Ulauncher/files/4919764/last.log)
