### ISSUE TITLE
Gitlab ulanucher failed to install

### ISSUE THREAD

**Issue by elue** [Ulauncher/Ulauncher#418]
Message: 'com.github.brpaz.ulauncher-gitlab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-gitlab'

```

**Comment by friday** [comment]
#273 most likely

**Comment by gornostal** [comment]
@elue could you please update the description using the issue template?

I need more details.

Thanks

**Comment by friday** [comment]
Closing this. This should be handled better now so you see an error message with missing python dependencies. If it's a binary dependency you should still see an error message about it. See #767
