### ISSUE TITLE
KeyError when I install any extension

### ISSUE THREAD

**Issue by OSPK** [Ulauncher/Ulauncher#432]
### Steps to reproduce
1.Open you launcher preferences
2. Install any extension
3. Save

### Current behavior
Message: 'com.github.ulauncher.ulauncher-kill'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.ulauncher.ulauncher-kill'

```

### Expected behavior
Extension save

### Environment
**Ulauncher version**: 5.3
**Linux distro**: Manjaro i3
**Desktop environment**: i3

### Logs
I have checked the extension, I have all dependencies installed. In logs when i add the extension i get this, it seems that ws server is not running

```
com.github.ulauncher.ulauncher-kill | 2019-09-25 19:22:17,855 | DEBUG | websocket: debug() | Connecting proxy...
com.github.ulauncher.ulauncher-kill | 2019-09-25 19:22:17,857 | ERROR | ulauncher.api.client.Client: on_error() | WS Client error failed CONNECT via proxy status: 502
com.github.ulauncher.ulauncher-kill | 2019-09-25 19:22:17,857 | WARNING | ulauncher.api.client.Client: on_close() | Connection closed. Exiting
com.github.ulauncher.ulauncher-kill | 2019-09-25 19:22:17,857 | DEBUG | ulauncher.api.client.Extension: trigger_event() | No listeners for event SystemExitEvent
2019-09-25 19:22:18,361 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ulauncher.ulauncher-kill" was terminated with code 0

```

**Comment by gornostal** [comment]
Looks like you have proxy configuration enabled on your machine, and for some reason it also uses it for connections to localhost

Could you check if `no_proxy` env var is set to some value?
`echo $no_proxy`

**Comment by OSPK** [comment]
oh, thankyou. This is exactly what it was. Ive added ```no_proxy``` var and now it is working fine. Marking the issue closed.
