### ISSUE TITLE
Error integration with Todoist extension saving changes when api is filled

### ISSUE THREAD

**Issue by Mateolegi** [Ulauncher/Ulauncher#439]
Message: 'com.github.cmuench.ulauncher-todoist'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.cmuench.ulauncher-todoist'

```

**Comment by brpaz** [comment]
I believe you are missing some dependency required by the extension. 

Another one related to #274. ;(
