### ISSUE TITLE
Extensions tab cannot open

### ISSUE THREAD

**Issue by ifi-milan** [Ulauncher/Ulauncher#455]
### Steps to reproduce
1. Open ULauncher preferences
2. Open Extensions tab
3. The error popup opens immediately

If there is an option to uninstall the extensions from the command line, please let me know so I could uninstall all of them and start fresh. Thanks

### Current behavior
Currently the error happens as described above. Happens for the past several months I just didn't have time to deal with it.

### Expected behavior
To be able to open the ulauncher extensions tab normally.

### Environment
**Ulauncher version**: 5.3.0
**Linux distro**: Linux Mint 19.2
**Desktop environment**: Cinnamon

### Logs

Message: 'ascii' codec can't decode byte 0xc4 in position 148: ordinal not in range(128)
Error Name: UnhandledError
Type: UnicodeDecodeError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    assert callback_name
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 393, in prefs_extension_get_all
    shortcuts.remove(req_data['id'])
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 452, in _get_all_extensions
    # Helpers
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionPreferences.py", line 35, in create_instance
    return cls(ext_id, ExtensionManifest.open(ext_id))
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 52, in open
    return cls(extension_id, read_manifest(extension_id, extensions_dir), extensions_dir)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 132, in read_manifest
    return load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 148: ordinal not in range(128)

```

**Comment by gornostal** [comment]
@ifi-milan it's probably caused by malformed `manifest.json` file of some extension that you have installed previously.
Try running the latest version of ulauncher and then if the issue exists attach your `~/.config/ulauncher/extensions.json`
