### ISSUE TITLE
ascii encoding error in cache files after upgrade from 4.4 to 5.4 (Python 2 to Python 3)

### ISSUE THREAD

**Issue by DorianScholz** [Ulauncher/Ulauncher#464]
### Steps to reproduce
1. upgrade Ulauncher from 4.4 to 5.4

### Current behavior
Console shows:

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3/dist-packages/ulauncher/search/apps/app_watcher.py", line 148, in start
>     for app in find_apps_cached():
>   File "/usr/lib/python3/dist-packages/ulauncher/utils/desktop/reader.py", line 101, in find_apps_cached
>     cache = KeyValueDb(desktop_file_cache_dir).open()
>   File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 35, in open
>     self.set_records(pickle.load(_in))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 76: ordinal not in range(128)

No Application are found in the launcher.

### Expected behavior
Clear obsolete ascii cache by itself and start normally.

### Workaround
Manually delete cache files in ~/.cache/ulauncher and restart ulauncher.

### Environment
**Ulauncher version**: 5.4.0
**Linux distro**: Ubuntu 16.04
**Desktop environment**: Gnome Flashback

**Comment by rprihoda** [comment]
This is still a problem on my machine regardless of deleting cache. Fedora 30 / GNOME Shell 3.32.2

**Comment by friday** [comment]
Closing this for inactivity. It probably only happened if you use Ulauncher before the python3 upgrade (5.0.0). And 6.0.0 will use json files instead, so it hasn't already been fixed it should be by then.
