### ISSUE TITLE
Empty ulauncher : _pickle.UnpicklingError: unpickling stack underflow

### ISSUE THREAD

**Issue by arthurlogilab** [Ulauncher/Ulauncher#469]
### Steps to reproduce
1. Launch ulauncher
2. type in the name of a application
3. nothing is displayed

### Current behavior

When typing in ulauncher it doesn't display any applications, on the shortcuts for the plugins. 

In the log I get two tracebacks : 

``` 
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/app_watcher.py", line 148, in start
    for app in find_apps_cached():
  File "/usr/lib/python3/dist-packages/ulauncher/utils/desktop/reader.py", line 101, in find_apps_cached
    cache = KeyValueDb(desktop_file_cache_dir).open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 35, in open
    self.set_records(pickle.load(_in))
_pickle.UnpicklingError: unpickling stack underflow


2019-11-19 08:57:53,970 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 169, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 35, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input


```

Solved it by : 

```
rm $HOME/.cache/ulauncher_cache/*.db
```

(then realised it might have been useful to keep them for debugging this problem or trying to repair the files). 

I think theses files were "corrupted" when the disk became full. 

### Environment
**Ulauncher version**:  5.4.0-0ubuntu1ppa1~bionic
**Linux distro**: Ubuntu bionic
**Desktop environment**: awesomewm

**Comment by KuenzelIT** [comment]
I had a similar problem and fixed it using 

```bash
rm $HOME/.local/share/ulauncher/*
```

And reinstalling ulauncher, although that might not be needed.

**Comment by gornostal** [comment]
Thanks for reporting the issue. It should be in the next release. I'll post an update here once it's available

**Comment by gornostal** [comment]
The fix is released with Ulauncher v5.6.0

**Comment by arthurlogilab** [comment]
Thanks !

**Comment by jhquentin** [comment]
it occurs in 5.7.5 too.
rm $HOME/.local/share/ulauncher/* solves the issue,.
