### ISSUE TITLE
No application showing up (.desktop parsing error)

### ISSUE THREAD

**Issue by Karmak23** [Ulauncher/Ulauncher#474]
Starting `ulauncher` from the console :

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/ulauncher/search/apps/app_watcher.py", line 148, in start
    for app in find_apps_cached():
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/desktop/reader.py", line 101, in find_apps_cached
    cache = KeyValueDb(desktop_file_cache_dir).open()
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/db/KeyValueDb.py", line 35, in open
    self.set_records(pickle.load(_in))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 67: ordinal not in range(128)
```

Thus, **no** application can be completed. other completion types work as expected.

# Environment
**Ulauncher version**: 5.4
**Linux distro**: Arch
**Desktop environment**: MATE

### Logs

`ulauncher -v` displays nothing, it just returns to command line.

**Comment by gornostal** [comment]
> ulauncher -v displays nothing, it just returns to command line.

@Karmak23 could you stop ulauncher first and then run from the command line?
If ulauncher is running you typing in `ulauncher` in command line will do nothing, as you noticed.

**Comment by friday** [comment]
Perhaps not a proper solution, but if anyone has issues like this, in particular after upgrading Ulauncher I would try deleting the cache databases `rm ~/.cache/ulauncher_cache/*.db`

**Comment by ibot3** [comment]
I have a similar problem since a few days: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 163, in on_input_changed
    Search.get_instance().on_query_change(self._get_user_query())
  File "/usr/lib/python3.8/site-packages/ulauncher/search/Search.py", line 40, in on_query_change
    self._choose_search_mode(query).handle_query(query).run()
  File "/usr/lib/python3.8/site-packages/ulauncher/search/apps/AppSearchMode.py", line 22, in handle_query
    result_list = self.app_db.find(query)
  File "/usr/lib/python3.8/site-packages/ulauncher/search/apps/AppDb.py", line 150, in find
    result_list.append(AppResultItem(rec))
  File "/usr/lib/python3.8/site-packages/ulauncher/search/apps/AppResultItem.py", line 16, in __init__
    self._app_stat_db = AppStatDb.get_instance()
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/ulauncher/search/apps/AppStatDb.py", line 18, in get_instance
    return cls(os.path.join(DATA_DIR, 'app_stat_v2.db')).open()
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 0: invalid start byte
```
This error appears for every character I type. ULauncher doesn't show any applications, however extensions are working.

I already tried to remove the cache databases with no success. Starting without extension also doesn't help.

**Comment by thob** [comment]
same here

` ulauncher
2020-03-07 12:53:50,916 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 170, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
2020-03-07 12:53:51,515 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 170, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
2020-03-07 12:53:51,516 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 163, in on_input_changed
    Search.get_instance().on_query_change(self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
2020-03-07 12:53:52,648 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 170, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
2020-03-07 12:53:52,654 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 163, in on_input_changed
    Search.get_instance().on_quer`

**Comment by ibot3** [comment]
I could fix the problem by deleting `.local/share/ulauncher`. I copied the `extension` folder before to keep my extensions.
