### ISSUE TITLE
Crashed when adding

### ISSUE THREAD

**Issue by thenitai** [Ulauncher/Ulauncher#479]
**Steps to reproduce:**
Add extension and add API key. Click on save

**Ulauncher version**: lastest
**Linux distro**: PopOS 19.10
**Desktop environment**: Gnome 3.34.1

**Logs**:

Message: 'com.github.cmuench.ulauncher-todoist'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 417, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.cmuench.ulauncher-todoist'

```

**Comment by friday** [comment]
#273

**Comment by gornostal** [comment]
@thenitai you need to install `todoistext` manually
