### ISSUE TITLE
Extensions are blocking start of Ulauncher

### ISSUE THREAD

**Issue by K4S1** [Ulauncher/Ulauncher#482]
### Steps to reproduce
1. i'm not sure how to re produce the error :-(
2.
3.

### Current behavior
Can only start ulaunger with "ulauncher --no-extensions"
And can't seems to find a way to disable extensions one by one to find witch failing.

### Expected behavior
start ulaunger with extensions

### Environment
**Ulauncher version5.4.0:
**Linux distro**: MX linux 19
**Desktop environment**: xfce4

### Logs

Message: Expecting value: line 1 column 1 (char 0)
Error Name: UnhandledError
Type: JSONDecodeError

Stacktrace:
```


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 399, in prefs_extension_get_all
    return self._get_all_extensions()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 474, in _get_all_extensions
    extensions.append(self._get_extension_info(ext_id, prefs, error))
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 479, in _get_extension_info
    ext_db = ExtensionDb.get_instance()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDb.py", line 25, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueJsonDb.py", line 21, in open
    self.set_records(json.load(_in))
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
Application are telling me to report here. when going in config under extensions.

https://gist.github.com/K4S1/ac3dd08a7e69c62a705810aaafe9fde4

Any help how to disable/remove extensions manully, when I can't du it from ulauncher application any more ?

Thanks in advance :)

**Comment by K4S1** [comment]
Figured it out.

found the ~/.config/ulauncher/extensions.json had gone complete empty after a computer crash.
I simply delete the file and removed all folders inside: ~/.local/share/ulauncher/extensions/*
Now I could start ulauncher normal again.
But need to reinstall all my extensions... that just life ;-)
