### ISSUE TITLE
breaks after token insert and save

### ISSUE THREAD

**Issue by pwnyprod** [Ulauncher/Ulauncher#503]
Message: 'com.github.brpaz.ulauncher-github'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 425, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-github'

```

### Steps to reproduce
1. download extension
2. insert access token
3. click save and crashed

### Current behavior

breaks :man_shrugging: 

### Expected behavior

works :man_shrugging: 

### Environment
**Ulauncher version**:
**Linux distro**: ubuntu 19.10
**Desktop environment**: Gnome

**Comment by gornostal** [comment]
Looks like the extension requires `PyGithub` package: https://github.com/brpaz/ulauncher-github#requirements
