### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by snakedye** [Ulauncher/Ulauncher#531]
### Steps to reproduce
1.
2.
3.

### Environment
**Ulauncher version**:
**Linux distro**:
**Desktop environment**:

### Logs
 
Message: 'com.github.brpaz.ulauncher-lipsum'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-lipsum'

```

**Comment by gornostal** [comment]
Looks like that package requires `lorem`

Try `sudo pip install lorem`
