### ISSUE TITLE
Some extensions crashed

### ISSUE THREAD

**Issue by ivan-tretyak** [Ulauncher/Ulauncher#550]
### Steps to reproduce

1. Install Ulauncher from repository.

2. Open Ulauncher, settings -> extensions -> add extensions and paste URL extension

3. Paste URL extension.

### Current behavior

Some extensions crashed.

### Expected behavior

Extensions work.

### Environment
**Ulauncher version**: ulauncher-5.7.5-1.fc32.noarch
**Linux distro**: Fedora 32
**Desktop environment**: GNOME on xorg

###Error message:

Message: 'com.github.isacikgoz.ukill'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.isacikgoz.ukill'

```
All crashed extensions have a same trouble.

I'm trying to add:

1. https://github.com/isacikgoz/ukill [crashed]
2. https://github.com/Ulauncher/ulauncher-emoji  [crashed]
3. https://github.com/brpaz/ulauncher-file-search [succefull install]
4. https://github.com/rkarami/ulauncher-gitmoji [succefull install]
5. https://github.com/Ulauncher/ulauncher-kill  [crashed]
### Logs

https://gist.github.com/ivan-tretyak/e9137dd985bb1a22fc608b2aaf81d5ee

**Comment by friday** [comment]
See #767
