### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by adarshbalu** [Ulauncher/Ulauncher#553]
Message: 'com.github.brpaz.ulauncher-github'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 417, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-github'

```

**Comment by Wirone** [comment]
@adarshbalu you need to install `gitlab` package with `pip3 install gitlab --user` - information is displayed in extension view along with `crashed` label.

**Comment by friday** [comment]
If this is still happening see #767. Hopefully you should be getting an error message advicing you to install the dependency as per above though.
