### ISSUE TITLE
Kanboard ulauncher crashes

### ISSUE THREAD

**Issue by emilioluque** [Ulauncher/Ulauncher#569]
Message: 'com.github.sebw.ulauncher-kanboard'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 417, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.sebw.ulauncher-kanboard'

**Comment by Chouchen** [comment]
It should be posted here: https://github.com/sebw/ulauncher-kanboard

**Comment by friday** [comment]
Haven't checked, but it's 99.99% likely due to a missing dependency #273

**Comment by sebw** [comment]
@emilioluque indeed, please open an issue in my repo and close this one here. Thanks.

**Comment by friday** [comment]
Closing this. This should be handled better now so you see an error message with missing python dependencies. See #767
