### ISSUE TITLE
Include extentsion requirements on extension page (was: Error when installing Brotab extension)

### ISSUE THREAD

**Issue by ptandler** [Ulauncher/Ulauncher#581]
Message: 'com.github.brpaz.ulauncher-brotab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 436, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-brotab'

```

**Comment by friday** [comment]
See https://github.com/brpaz/ulauncher-brotab#requirements

**Comment by ptandler** [comment]
Thanks for the hint, I'll try this.

Maybe I should rephrase the issue to include installation requirements on the extension pages, in this case on
https://ext.ulauncher.io/-/github-brpaz-ulauncher-brotab

I just haven't thought that I have to check another page for additional requirements & documentation.

**Comment by friday** [comment]
Yeah, it should be handled better. See #273 This issue is like 20% of the errors reported here.

**Comment by ptandler** [comment]
Yep, I can imagine. Automation would be cool.

**Comment by friday** [comment]
Closing this. This should be handled better now, showing the missing python libs, and it will be even better handled in the future. See #767
