### ISSUE TITLE
add extension UnhandledError

### ISSUE THREAD

**Issue by yinxiulong** [Ulauncher/Ulauncher#582]
**Steps to reproduce:**
_your steps to reproduce here_

**Ulauncher version**:5.4.1
**Linux distro**:  deepinV20
**Desktop environment**:

**Logs**:
 Message: <urlopen error [Errno 111] 拒绝连接>
Error Name: UnhandledError
Type: URLError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/io.ulauncher/files/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/opt/apps/io.ulauncher/files/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/opt/apps/io.ulauncher/files/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 400, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/opt/apps/io.ulauncher/files/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/opt/apps/io.ulauncher/files/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
    for ver in self.read_versions():
  File "/opt/apps/io.ulauncher/files/ulauncher/api/server/GithubExtension.py", line 110, in read_versions
    versions = self._read_json('master', 'versions.json')
  File "/opt/apps/io.ulauncher/files/ulauncher/api/server/GithubExtension.py", line 101, in _read_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] 拒绝连接>

```

Type: URLError
_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_

**Comment by friday** [comment]
Can you post the link to the extension you tried to add? :)

**Comment by johncyuan** [comment]
Should be a network problem, you can try to set up a proxy

**Comment by friday** [comment]
Closing this as it's stale and the log makes it too hard to figure out the problem or if it's even still a problem. The most recent version improved logging and extension error handling so if it happens again please create a new issue.
