### ISSUE TITLE
Extensions consistently failing to download.

### ISSUE THREAD

**Issue by Destarianon** [Ulauncher/Ulauncher#589]
**Steps to reproduce:**
Copy an extension URL from the "discover extensions" page into the "add extensions" menu, and hit enter.

**Ulauncher version**:5.8.0
**Linux distro**:Ubuntu Mate 20.04

**Stacktrace:
Message: HTTP Error 500: Internal Server Error
Error Name: UnhandledError
Type: HTTPError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 425, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 78, in download
    filename = download_zip(gh_ext.get_download_url(commit['sha']))
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 195, in download_zip
    filename, _ = urlretrieve(url, dest_zip)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

```

**Comment by Budhathoki356** [comment]
Yeah, I'm also getting the same problem.

**Comment by KuenzelIT** [comment]
I cannot reproduce the error. Can you provide a specific extension url where you get this error?

**Comment by friday** [comment]
#679
