### ISSUE TITLE
Brotab -Ulauncher Extension Chrome not working, KDE Plasma

### ISSUE THREAD

**Issue by ghost** [Ulauncher/Ulauncher#600]
Hey,
Dowĺoaded this extension from Ulaunchers extensions and this error came up. 
Looks like you have done a lot of extensions, hope you can get this one working! 

Message: 'com.github.brpaz.ulauncher-brotab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 436, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-brotab'

```

**Comment by friday** [comment]
You have to install the extension dependencies manually. See their github pages.

**Comment by friday** [comment]
Closing this. This should be handled better now so you see an error message with missing python dependencies. See #767
