### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by Brblol** [Ulauncher/Ulauncher#603]
I am getting the following error when I click Save after entering my personal hosted gitlab and access token

Message: 'com.github.brpaz.ulauncher-gitlab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-gitlab'

```

**Comment by friday** [comment]
All of these are duplicate issues: https://github.com/Ulauncher/Ulauncher/search?q=KeyError&type=issues

**Comment by friday** [comment]
Closing this. This should be handled better now so you see an error message with missing python dependencies. If it's a binary dependency you should still see an error message about it. See #767
