### ISSUE TITLE
Can't launch 

### ISSUE THREAD

**Issue by TheBlackguarde** [Ulauncher/Ulauncher#61]
I can't launch Ulauncher, the icon just flickers and nothing happen. I can launch it with
sudo ./bin/ulauncher -v --dev $@

I'm on Ubuntu 16.04.

**Comment by gornostal** [comment]
@TheBlackguarde try without sudo.
If I wrote you should run it with sudo, please let me know where.
Also, please post output or/and `~/.cache/ulauncher/last.log`

**Comment by TheBlackguarde** [comment]
When i run it without sudo it gives me this:

```
marlon@Marlon-HP-ENVY-15-Notebook-PC:~/Downloads/Ulauncher$ ./bin/ulauncher -v --dev $@
/home/marlon/Downloads/Ulauncher/ulauncher/__init__.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/home/marlon/Downloads/Ulauncher/ulauncher/ui/windows/UlauncherWindow.py:6: PyGIWarning: Keybinder was imported without specifying a version first. Use gi.require_version('Keybinder', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, Keybinder
/home/marlon/Downloads/Ulauncher/ulauncher/ui/windows/PreferencesUlauncherDialog.py:4: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2
/home/marlon/Downloads/Ulauncher/ulauncher/ui/AppIndicator.py:3: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, AppIndicator3
2017-02-22 12:20:08,741:DEBUG:ulauncher: set_up_logging() 'logging enabled'
Traceback (most recent call last):
  File "./bin/ulauncher", line 25, in <module>
    ulauncher.main()
  File "/home/marlon/Downloads/Ulauncher/ulauncher/__init__.py", line 48, in main
    set_up_logging(options)
  File "/home/marlon/Downloads/Ulauncher/ulauncher/helpers.py", line 73, in set_up_logging
    os.remove(log_file)
OSError: [Errno 13] Permission denied: '/home/marlon/.cache/ulauncher_cache/last.log'
```

I assume you meant  ~/.cache/ulauncher_cache/last.log 
This is the content of last.log

```
2017-02-22 12:13:05,396:INFO:ulauncher: main() 'Ulauncher version: VERSION'
2017-02-22 12:13:05,399:DEBUG:ulauncher: main() 'Starting a new instance...'
2017-02-22 12:13:05,426:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'ulauncher_window','destroy', 'on_destroy''
2017-02-22 12:13:05,426:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event''
2017-02-22 12:13:05,426:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event''
2017-02-22 12:13:05,428:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'input','key_press_event', 'on_input_key_press_event''
2017-02-22 12:13:05,429:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_mnu_about_activate''
2017-02-22 12:13:05,430:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_mnu_close_activate''
2017-02-22 12:13:05,430:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_preferences_dialog_destroyed''
2017-02-22 12:13:05,430:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_mnu_preferences_activate''
2017-02-22 12:13:05,430:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_input_changed''
2017-02-22 12:13:05,438:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/JB-jvisualvm-jdk9.desktop": constructor returned NULL'
2017-02-22 12:13:05,445:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/JB-mission-control-jdk9.desktop": constructor returned NULL'
2017-02-22 12:13:05,445:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/gnome-sudoku.desktop": constructor returned NULL'
2017-02-22 12:13:05,446:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/gnome-mahjongg.desktop": constructor returned NULL'
2017-02-22 12:13:05,449:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/pykaraoke.desktop": constructor returned NULL'
2017-02-22 12:13:05,451:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/gnome-mines.desktop": constructor returned NULL'
2017-02-22 12:13:05,456:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/vim.desktop": constructor returned NULL'
2017-02-22 12:13:13,764:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/pykaraoke_mini.desktop": constructor returned NULL'
2017-02-22 12:13:13,768:INFO:ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() 'Trying to bind app hotkey: <Primary>space'
2017-02-22 12:13:14,584:INFO:ulauncher.search.apps.app_watcher: start() 'Finished scanning directories for desktop files. Indexed 143 applications'
2017-02-22 12:13:14,591:DEBUG:ulauncher.search.apps.app_watcher: start() 'Start watching desktop files...'
```


I actually figured it out myself after looking at the logs. apparently the owner of the log file was root, probably because I ran a command during install with sudo. I made me the owner and now it works.

Thanks for the help anyways

**Comment by gornostal** [comment]
I'm glad the issue is resolved.
