### ISSUE TITLE
Crash on Keyword Change

### ISSUE THREAD

**Issue by NaEaP** [Ulauncher/Ulauncher#619]
### Steps to reproduce
1. Changed Brotab keyword from 'brotab' to 'tab'
2. Clicked saved
3. Crashed 
(ulauncher asked my to post this issue, so here I am.)

### Current behavior
Seems to just crash without any feedback.

### Expected behavior
Correctly change the keyword

### Environment
**Ulauncher version**: 5.8.0
**Linux distro**: Manjaro 20.1
**Desktop environment**: KDE

### Logs
Message: 'com.github.brpaz.ulauncher-brotab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 436, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-brotab'

```

**Comment by friday** [comment]
See #767 (this has been improved and will be improved more from our side)
