### ISSUE TITLE
Extension Crashed !

### ISSUE THREAD

**Issue by duckhaitong** [Ulauncher/Ulauncher#628]
Message: 'com.github.nesivmi.ulauncher-translate'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 436, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.nesivmi.ulauncher-translate'

```

**Comment by duckhaitong** [comment]
I fixed by install requirements.txt
```pip install -r requirements.txt```
log out and it did the trick
