### ISSUE TITLE
Python2 Required for `./ul build-preferences`

### ISSUE THREAD

**Issue by troycurtisjr** [Ulauncher/Ulauncher#651]
### Steps to reproduce
1. Try to build without Python2 installed

```
./data/preferences/node_modules/node-gyp/lib/configure.js:    var args = ['-c', 'import sys; print "%s.%s.%s" % sys.version_info[:3];']
```
This configure in the node module uses a print syntax that does not work with Python3.

### Expected behavior
Since Python2 is deprecated, I would think it shouldn't need to be installed.

### Environment
**Ulauncher version**: dev
**Linux distro**: fedora 33
**Desktop environment**: n/a

### Logs
```
error /root/Ulauncher/data/preferences/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /root/Ulauncher/data/preferences/node_modules/node-sass
Output:
Building: /usr/bin/node /root/Ulauncher/data/preferences/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/root/Ulauncher/data/preferences/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.14.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/bin/python3" in the PATH
gyp verb `which` succeeded /usr/bin/python3 /usr/bin/python3
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Linux 5.8.16-200.fc32.x86_64
gyp ERR! command "/usr/bin/node" "/root/Ulauncher/data/preferences/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/Ulauncher/data/preferences/node_modules/node-sass
gyp ERR! node -v v14.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by troycurtisjr** [comment]
And yes, I was running the build-preferences directly. I got unblocked by just building with the provided dev-container, but it still seemed like something that should be looked at.

**Comment by earboxer** [comment]
We should remove the dependency on node-sass (aren't css variables enough in $CURRENT_YEAR)?

And also remove dependency on phantom js (I've had trouble installing this on ARM systems -- using a docker container wouldn't solve this problem).

With those giants out of the way, building should be easier... I assume this would be worth the trouble, compared to rewriting the preferences page to not be a javascript application? (Currently it has accessibility issues, and screen size issues, which I want to fix).

**Comment by friday** [comment]
This is fixed by now
