### ISSUE TITLE
no module named 'ulauncher'

### ISSUE THREAD

**Issue by andersfylling** [Ulauncher/Ulauncher#655]
### Steps to reproduce
1. open a terminal
2. write `ulauncher`
3. hit enter

### Current behavior
outputs the following error:
```
➜ ulauncher
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
ModuleNotFoundError: No module named 'ulauncher'
```

### Expected behavior
no error to happen and ulauncher to start

### Environment
**Ulauncher version**: 5.9.0-1
**Linux distro**: arch 5.9.11-arch2-1
**Desktop environment**: sway 1.5.1

### Logs
```
➜ ulauncher -v
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
ModuleNotFoundError: No module named 'ulauncher'
```

Related: #556

**Comment by genghispirate** [comment]
had the same problem a few hours ago,
I reinstalled ulauncher it started working again, and kept all configs and extensions

**Comment by pakro** [comment]
> had the same problem a few hours ago,
> I reinstalled ulauncher (through AUR on archlinux) it started working again, and kept all configs and extensions

Reinstalled but having still the same issue. Did you install ulauncher-git or ulauncher?

**Comment by genghispirate** [comment]
> > had the same problem a few hours ago,
> > I reinstalled ulauncher (through AUR on archlinux) it started working again, and kept all configs and extensions
> 
> Reinstalled but having still the same issue. Did you install ulauncher-git or ulauncher?

Ulauncher, I ran yay -S ulauncher

**Comment by AlejandroME** [comment]
The issue seems to be caused by the bunch of Python libs that got updated today (December 2nd):

```
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-anytree (2.8.0-1 -> 2.8.0-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-asn1crypto (1.4.0-1 -> 1.4.0-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-msgpack (1.0.0-1 -> 1.0.0-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-chardet (3.0.4-5 -> 3.0.4-7)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-idna (2.10-1 -> 2.10-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-requests (2.24.0-1 -> 2.25.0-1)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-cachecontrol (0.12.6-1 -> 0.12.6-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pycparser (2.20-1 -> 2.20-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-cffi (1.14.3-1 -> 1.14.4-1)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-click (7.1.2-1 -> 7.1.2-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-configobj (5.0.6-7 -> 5.0.6-9)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-contextlib2 (0.6.0.post1-1 -> 0.6.0.post1-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-cryptography (3.2.1-1 -> 3.2.1-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-distlib (0.3.1-1 -> 0.3.1-2)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-distutils-extra (2.39-5 -> 2.39-8)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-fido2 (0.8.1-1 -> 0.8.1-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-webencodings (0.5.1-4 -> 0.5.1-6)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-html5lib (1.1-4 -> 1.1-5)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-levenshtein (0.12.0-8 -> 0.12.0-10)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-lxml (4.6.1-1 -> 4.6.2-1)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-toml (0.10.2-1 -> 0.10.2-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pep517 (0.9.1-1 -> 0.9.1-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-progress (1.5-3 -> 1.5-5)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-retrying (1.3.3-7 -> 1.3.3-9)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-resolvelib (0.5.1-1 -> 0.5.2-1)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pyopenssl (19.1.0-2 -> 20.0.0-1)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pip (20.2-1 -> 20.2-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-psutil (5.7.3-1 -> 5.7.3-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pycups (2.0.1-1 -> 2.0.1-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pycurl (7.43.0.6-1 -> 7.43.0.6-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pyenchant (3.1.1-2 -> 3.1.1-4)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pygments (2.7.2-1 -> 2.7.2-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pyinotify (0.9.6-7 -> 0.9.6-9)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pymongo (3.11.0-1 -> 3.11.1-1)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pypandoc (1.5-2 -> 1.5-4)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pyscard (2.0.0-1 -> 2.0.0-2)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pytoml (0.1.21-4 -> 0.1.21-6)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pyusb (1.1.0-1 -> 1.1.0-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-pyxdg (0.26-6 -> 0.26-8)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-regex (2020.11.13-1 -> 2020.11.13-2)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-urwid (2.1.1-1 -> 2.1.1-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python-websocket-client (0.57.0-1 -> 0.57.0-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python2-appdirs (1.4.4-1 -> 1.4.4-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python2-dbus (1.2.16-1 -> 1.2.16-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python2-pyparsing (2.4.7-1 -> 2.4.7-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python2-six (1.15.0-1 -> 1.15.0-3)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python2-packaging (20.4-1 -> 20.7-1)
[2020-12-02T05:06:56-0500] [ALPM] upgraded python2-psutil (5.7.3-1 -> 5.7.3-3)
```

This update does not only broke `ulauncher`, but in my case my laptop got stuck in a bootloop because `optimus-manager` is affected by this.
`mate` got affected by this (crashing constantly), gpg and the Yubikey daemon got affected by this.

I rolled back this upgrade and everything went to its normal state.

**Comment by andersfylling** [comment]
I'm surprised there's no version control..

**Comment by pakro** [comment]
> > > had the same problem a few hours ago,
> > > I reinstalled ulauncher (through AUR on archlinux) it started working again, and kept all configs and extensions
> > 
> > 
> > Reinstalled but having still the same issue. Did you install ulauncher-git or ulauncher?
> 
> Ulauncher, I ran yay -S ulauncher

I've deleted ./cache/yay/ulauncher folder and reinstalled. It is working now properly again. This also worked for other python based applications. Just need to ensure that it clean builds and uses the newly updated python packages.

Thank you @genghispirate!
