### ISSUE TITLE
Cannot Save Github extension

### ISSUE THREAD

**Issue by JoanaMota** [Ulauncher/Ulauncher#671]
Message: 'com.github.brpaz.ulauncher-github'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-github'

```

### Steps to reproduce
1.
2.
3.

### Environment
**Ulauncher version**:
**Linux distro**:
**Desktop environment**:

**Comment by gornostal** [comment]
That extension requires some extra dependencies: https://github.com/brpaz/ulauncher-github/blob/master/requirements.txt
You can install them with `pip install -r requirements.txt`
