### ISSUE TITLE
Handle connectivity issues when adding extensions

### ISSUE THREAD

**Issue by joezhouchenye** [Ulauncher/Ulauncher#679]
### Steps to reproduce
1. Ubuntu 20.04
2. Launch Ulauncher form show applications
3. No response when trying to add an extension

### Current behavior

Using the steps showing above, I cannot add an extension.
I have to start a terminal and launch ulauncher from there and the add extension feature is working now, although some error messages are showing in the terminal.

### Expected behavior

The add extension feature should work, no matter the way it is launched.

### Environment
**Ulauncher version**: v5.9.0
**Linux distro**: ubuntu 20.04
**Desktop environment**: gnome

**Comment by BoltLi** [comment]
I came across the same problems, though my linux environment is KDE.
And after I try to add a extension to ulauncher, some error came out from the terminal, that is:

file:///usr/share/ulauncher/preferences/dist/static/js/app.c7a36559c1151f811a88.js:4919:18: CONSOLE ERROR TypeError: e.cancel is not a function. (In 'e.cancel()', 'e.cancel' is undefined)
2021-01-17 22:03:30,170 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 425, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
    for ver in self.read_versions():
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 110, in read_versions
    versions = self._read_json('master', 'versions.json')
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 101, in _read_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
2021-01-17 22:06:12,571 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | GithubExtensionError: Invalid GithubUrl: https://github.com/norbr9/ulauncher-youtube-search/
file:///usr/share/ulauncher/preferences/dist/static/js/app.c7a36559c1151f811a88.js:4919:18: CONSOLE ERROR TypeError: e.cancel is not a function. (In 'e.cancel()', 'e.cancel' is undefined)

**Comment by gornostal** [comment]
@BoltLi in your case you Ulauncher can't access Github API for some reason.
What do you see in console if you run this command: `curl https://api.github.com/`?

**Comment by gornostal** [comment]
@joezhouchenye I don't see your logs.
What extension are you trying to install, BTW?

**Comment by BoltLi** [comment]
> @BoltLi in your case you Ulauncher can't access Github API for some reason.
> What do you see in console if you run this command: `curl https://api.github.com/`?

I try the command, with the results as follows:
$ curl https://api.github.com/
{
  "current_user_url": "https://api.github.com/user",
  "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
  "authorizations_url": "https://api.github.com/authorizations",
  "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
  "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://api.github.com/user/emails",
  "emojis_url": "https://api.github.com/emojis",
  "events_url": "https://api.github.com/events",
  "feeds_url": "https://api.github.com/feeds",
  "followers_url": "https://api.github.com/user/followers",
  "following_url": "https://api.github.com/user/following{/target}",
  "gists_url": "https://api.github.com/gists{/gist_id}",
  "hub_url": "https://api.github.com/hub",
  "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://api.github.com/issues",
  "keys_url": "https://api.github.com/user/keys",
  "label_search_url": "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
  "notifications_url": "https://api.github.com/notifications",
  "organization_url": "https://api.github.com/orgs/{org}",
  "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_teams_url": "https://api.github.com/orgs/{org}/teams",
  "public_gists_url": "https://api.github.com/gists/public",
  "rate_limit_url": "https://api.github.com/rate_limit",
  "repository_url": "https://api.github.com/repos/{owner}/{repo}",
  "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://api.github.com/gists/starred",
  "user_url": "https://api.github.com/users/{user}",
  "user_organizations_url": "https://api.github.com/user/orgs",
  "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
}

**Comment by gornostal** [comment]
@BoltLi apparently only Ulauncher app cannot connect to Github, which is weird.
Maybe you have some proxy settings enabled?
Try to exit ulauncher and then run it from the same console where you ran `curl`. It's going to be even weirder if you get Connection Refused error then.

**Comment by BoltLi** [comment]
oh, maybe that's becase the proxy problem, cause when I `ping github.com`,the ttl is bigger than natural. I give up trying this for some other one already meet my need. Anyway, Thanks a lot!

**Comment by liuyonghao156** [comment]
@gornostal Is there a way to manually add extensions without relying on an active Internet connection? In mainland China we have a very unstable GitHub connection.

**Comment by friday** [comment]
Renamed this to be more specific.

We could do two things to improve the situation:
1. Show a more friendly error message (also perhaps showing if the connection was blocked or rate limited by github)
2. Add an easier way to install pre-downloaded extensions locally.
