### ISSUE TITLE
cannot be added to Ulauncher

### ISSUE THREAD

**Issue by OmarShawky1** [Ulauncher/Ulauncher#680]
### Steps to reproduce
1.Just try to add extention to Ulauncher

### Current behavior
cannot be added

### Expected behavior
should be saved to my extentions

### Environment
**Ulauncher version**: 2.0
**Linux distro**: Elementary OS Hera 5.1.7 based on Ubuntu 18.04
**Desktop environment**: Pantheon

### Logs
Message: 'com.github.the-lay.ulauncher-spotify-api'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.the-lay.ulauncher-spotify-api'

```

**Comment by gornostal** [comment]
The extension expects [these](https://github.com/the-lay/ulauncher-spotify-api/blob/master/requirements.txt) two dependencies installed: `pip install -r requirements.txt`

**Comment by the-lay** [comment]
Just noticed this issue. If someone finds this issue and is also having the same trouble with `ulauncher-spotify-api` extension, please see [Installation section](https://github.com/the-lay/ulauncher-spotify-api#installation) and please report extension problems to the extension repository, not ulauncher directly.
