### ISSUE TITLE
I have bug on your new update

### ISSUE THREAD

**Issue by MiladMohebnia** [Ulauncher/Ulauncher#687]
Message: 'com.github.brpaz.ulauncher-vscode-projects'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-vscode-projects'

```

**Comment by gornostal** [comment]
Have you tried to report the issue on the maintainers  Github?

**Comment by MiladMohebnia** [comment]
no!

**Comment by gornostal** [comment]
Most likely this issue occurs because of the missing dependency: https://github.com/brpaz/ulauncher-vscode-projects#install
Please open the bug on https://github.com/brpaz/ulauncher-vscode-projects if that doesn't help.
