### ISSUE TITLE
Failed to install via `python setup.py install`

### ISSUE THREAD

**Issue by lebensterben** [Ulauncher/Ulauncher#691]
### Steps to reproduce
1. `git clone` the source code at checkout the latest release commit.
2. `sudo python setup.py install --prefix=/usr/local --optimize=1`

### Error
Cannot install. Error attached below.

### Environment
**Ulauncher version**:
**Linux distro**: Clear Linux
**Desktop environment**: XMonad

### Logs
```
Writing /usr/local/lib/python3.9/site-packages/ulauncher-_VERSION_-py3.9.egg-info
Traceback (most recent call last):
  File "/home/lucius/GitHub/Ulauncher/setup.py", line 242, in <module>
    main()
  File "/home/lucius/GitHub/Ulauncher/setup.py", line 192, in main
    DistUtilsExtra.auto.setup(
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 100, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/lucius/GitHub/Ulauncher/setup.py", line 121, in run
    desktop_file = move_desktop_file(self.root, target_data, self.prefix)
  File "/home/lucius/GitHub/Ulauncher/setup.py", line 51, in move_desktop_file
    old_desktop_path = os.path.normpath(root + target_data + '/share/applications')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by troycurtisjr** [comment]
This isn't the installation procedure. Check out the README for instructions for running from source.
