### ISSUE TITLE
Fixed. Download my extension

### ISSUE THREAD

**Issue by seon22break** [Ulauncher/Ulauncher#695]
## Question

Hi. I have developed a small extension and when I install it from the launcher panel, I get an error in Python that I am not able to solve. I don't know if the error is caused by the content of my extension or by the download from github. 

However when I use the extension in development it works correctly. 

`2021-02-17 16:07:24,617 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. HTTPError: HTTP Error 422: Unprocessable Entity
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 80, in find_compatible_version
    return self.get_commit(sha_or_branch)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 89, in get_commit
    resp = json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
`

**Comment by nurgasemetey** [comment]
It seems more about `HTTP error`, you can narrow issue by calling sample endpoint.

**Comment by troycurtisjr** [comment]
You will need to provide a bit more detail about what you have tried. For example, what is the URL of the extension, is that the URL you tried when you had this error?

**Comment by seon22break** [comment]
The error occurs when I use the url of the extension https://github.com/seon22break/Bitcoin-Exchange

**Comment by seon22break** [comment]
Sorry, I was able to fix my mistake. I had the wrong branch in the versions file.  I am blind...
