### ISSUE TITLE
Ulauncher unable to search apps after latest update

### ISSUE THREAD

**Issue by MENOZE** [Ulauncher/Ulauncher#699]
**Steps to reproduce:**
Update Linux Mint 20.1 to the Latest version. Before a certain update, Ulauncher was able to populate
the search bar with local apps. Now nothing shows up but the search bar.

**Ulauncher version**: v5.10.0
**Linux distro**: Linux Mint 20.1 Ulyssa 64-bit 
**Desktop environment**: MATE 1.24.0

**Logs**:
2021-02-25 07:51:18,060 | INFO | ulauncher: main() | Ulauncher version 5.10.0
2021-02-25 07:51:18,060 | INFO | ulauncher: main() | Extension API version 2.0.0
2021-02-25 07:51:18,060 | INFO | ulauncher: main() | GTK+ 3.24.20
2021-02-25 07:51:18,061 | INFO | ulauncher: main() | Is Wayland: False
2021-02-25 07:51:18,061 | INFO | ulauncher: main() | Wayland compatibility: off
2021-02-25 07:51:18,078 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2021-02-25 07:51:18,080 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2021-02-25 07:51:18,080 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2021-02-25 07:51:18,081 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2021-02-25 07:51:18,081 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2021-02-25 07:51:18,081 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2021-02-25 07:51:18,081 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2021-02-25 07:51:18,082 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2021-02-25 07:51:18,082 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2021-02-25 07:51:18,082 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2021-02-25 07:51:18,083 | DEBUG | ulauncher.utils.display: get_screens() | Found 2 monitor(s)
2021-02-25 07:51:18,083 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2021-02-25 07:51:18,083 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 1920, Y: 0, W: 1280, H: 1024
2021-02-25 07:51:18,106 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2021-02-25 07:51:18,107 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
Exception in thread Thread-1:
Traceback (most recent call last):
2021-02-25 07:51:18,107 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/app_watcher.py", line 168, in start
    for app in find_apps_cached():
  File "/usr/lib/python3/dist-packages/ulauncher/utils/desktop/reader.py", line 103, in find_apps_cached
    cache = KeyValueDb(desktop_file_cache_dir).open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
_pickle.UnpicklingError: invalid load key, '\x04'.
2021-02-25 07:51:18,118 | DEBUG | ulauncher.utils.semver: parse_range() | range ^2.0.0 False
2021-02-25 07:51:18,118 | DEBUG | ulauncher.utils.semver: parse_range() | hyphen replace ^2.0.0
2021-02-25 07:51:18,118 | DEBUG | ulauncher.utils.semver: parse_range() | comparator trim ^2.0.0, re.compile('(\\s*)((?:<|>)?=?)\\s*([v=\\s]*([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-?((?:[0-9]+|\\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\\.(?:[0-9]+|\\d*[a-zA-Z-][a-zA-Z0-9-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?|[v, re.MULTILINE)
2021-02-25 07:51:18,118 | DEBUG | ulauncher.utils.semver: parse_comparator() | comp ^2.0.0
2021-02-25 07:51:18,118 | DEBUG | ulauncher.utils.semver: repl() | caret ^2.0.0 ^2.0.0 2 0 0 None
2021-02-25 07:51:18,118 | DEBUG | ulauncher.utils.semver: repl() | caret return >=2.0.0 <3.0.0
2021-02-25 07:51:18,118 | DEBUG | ulauncher.utils.semver: parse_comparator() | caret >=2.0.0 <3.0.0
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: parse_comparator() | tildes >=2.0.0 <3.0.0
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: replace_xranges() | replaceXRanges >=2.0.0 <3.0.0 False
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: repl() | xrange >=2.0.0 >=2.0.0 >= 2 0 0 None
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: repl() | xrange gtlt=>= any_x=False
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: repl() | xRange return >=2.0.0
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: repl() | xrange <3.0.0 <3.0.0 < 3 0 0 None
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: repl() | xrange gtlt=< any_x=False
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: repl() | xRange return <3.0.0
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: parse_comparator() | xrange >=2.0.0 <3.0.0
2021-02-25 07:51:18,119 | DEBUG | ulauncher.utils.semver: replace_stars() | replaceStars >=2.0.0 <3.0.0 False
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: parse_comparator() | stars >=2.0.0 <3.0.0
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: __init__() | comparator: >=2.0.0 False
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: parse() | parse comp=>=2.0.0
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: __init__() | SemVer 2.0.0, False
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: __init__() | comparator: <3.0.0 False
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: parse() | parse comp=<3.0.0
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: __init__() | SemVer 3.0.0, False
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: format() | Range format >=2.0.0 <3.0.0
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: __init__() | SemVer 2.0.0, False
2021-02-25 07:51:18,120 | DEBUG | ulauncher.utils.semver: test() | Comparator, test 2.0.0, False
2021-02-25 07:51:18,121 | DEBUG | ulauncher.utils.semver: cmp() | cmp: >=
2021-02-25 07:51:18,121 | DEBUG | ulauncher.utils.semver: compare() | SemVer.compare 2.0.0 False 2.0.0
2021-02-25 07:51:18,121 | DEBUG | ulauncher.utils.semver: compare() | compare result 0
2021-02-25 07:51:18,121 | DEBUG | ulauncher.utils.semver: test() | Comparator, test 2.0.0, False
2021-02-25 07:51:18,121 | DEBUG | ulauncher.utils.semver: cmp() | cmp: <
2021-02-25 07:51:18,121 | DEBUG | ulauncher.utils.semver: compare() | SemVer.compare 2.0.0 False 3.0.0
2021-02-25 07:51:18,121 | DEBUG | ulauncher.utils.semver: compare() | compare result -1
2021-02-25 07:51:18,124 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-digiralocean" started. PID 3787
2021-02-25 07:51:18,147 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2021-02-25 07:51:18,245 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.brpaz.ulauncher-digiralocean" connected
2021-02-25 07:51:18,245 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.brpaz.ulauncher-digiralocean"

(ulauncher:3777): Gdk-CRITICAL **: 07:51:18.273: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2021-02-25 07:51:21,253 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 181, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
2021-02-25 07:51:21,255 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 174, in on_input_changed
    Search.get_instance().on_query_change(self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
2021-02-25 07:51:21,621 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 181, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
2021-02-25 07:51:21,622 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 174, in on_input_changed
    Search.get_instance().on_query_change(self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input

**Comment by Call1st0** [comment]
Had the same issue. I've just reinstalled the deb package and it started working correctly.

**Comment by troycurtisjr** [comment]
Pickling is Python version dependent, and I'm betting your Python minor version increased with the upgrade. Try deleting `~/.cache/ulauncher_cache` and starting it back up.

**Comment by MENOZE** [comment]
Okay. I went to another application, but I will install and try it again.

**Comment by friday** [comment]
Pickle load issue indicate the file was corrupted. Since pickle is a binary format that only Python can load there's a bit of black box magic happening which is hard to debug. We're switching to JSON for version 6.0.0, and in addition the PR I just linked ^ will treat these errors as non fatal and fallback to use empty data and recreate the files.

**Comment by ebennett1980** [comment]
Same issue with ubuntu 20.04, tried older packages all the way back to 5.14.0 

Every keypress in the popup causes;

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 175, in on_input_changed
    Search.get_instance().on_query_change(self._get_user_query())
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 40, in on_query_change
    self._choose_search_mode(query).handle_query(query).run()
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppSearchMode.py", line 22, in handle_query
    result_list = self.app_db.find(query)
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppDb.py", line 153, in find
    result_list.append(AppResultItem(rec))
  File "/usr/lib/python3/dist-packages/ulauncher/search/apps/AppResultItem.py", line 15, in __init__
    self._query_history = QueryHistoryDb.get_instance()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/search/QueryHistoryDb.py", line 13, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 37, in open
    self.set_records(pickle.load(_in))
_pickle.UnpicklingError: invalid load key, '\x00'.


If run in a terminal

**Comment by friday** [comment]
@ebennett1980 Delete the file ~/.local/share/ulauncher/query_history.db

**Comment by friday** [comment]
Maybe try all the other db files in that directory also if that doesn't work

**Comment by ebennett1980** [comment]
> Maybe try all the other db files in that directory also if that doesn't work

Deleting the query history didn't work but deleting the entire directory did. Thanks!
