### ISSUE TITLE
YouTube Search

### ISSUE THREAD

**Issue by drosan2000** [Ulauncher/Ulauncher#726]
Message: 'com.github.lifeofcoding.ulauncher-youtube'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.lifeofcoding.ulauncher-youtube'

```

**Comment by troycurtisjr** [comment]
This looks like you didn't install the dependencies needed by the extension. In the case of the youtube extension I'm thinking it is `beautifulsoup`. The error message could certainly be more helpful ;)

**Comment by friday** [comment]
For specific extension support, see #767
