### ISSUE TITLE
Argument 0 does not allow None as a value

### ISSUE THREAD

**Issue by przbadu** [Ulauncher/Ulauncher#758]
### Steps to reproduce
1. Fresh installation of Ubuntu 20.04
2. Install `Ulauncher` by either downloading `.deb` file or by using `sudo apt install ulauncher` (version I have issue with: `ulauncher 5.11.0`)
3. Type `ulauncher` in terminal

### Current behavior

```
ulauncher
2021-07-03 22:29:59,026 | WARNING | ulauncher.utils.image_loader: load_image() | Could not load image /usr/share/ulauncher/media/gear.svg. E: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/usr/share/ulauncher/media/gear.svg” (3)
2021-07-03 22:29:59,026 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 128, in main
    window = UlauncherWindow.get_instance()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 55, in get_instance
    return cls()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 65, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 98, in finish_initializing
    self.init_theme()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 237, in init_theme
    self._render_prefs_icon()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 388, in _render_prefs_icon
    surface = Gdk.cairo_surface_create_from_pixbuf(prefs_pixbuf, scale_factor, self.get_window())
TypeError: Argument 0 does not allow None as a value
```

Get above issue, and ulauncher isn't launched because of that.

### Expected behavior

- It should open ulauncher

### Environment
**Ulauncher version**: ulauncher 5.11.0
**Linux distro**: Ubuntu 20.04.2 LTS (Focal)
**Desktop environment**: Gnome

**Comment by przbadu** [comment]
Ah if I open `Ulauncher` from program list, it is working just fine. closing it.
