### ISSUE TITLE
Extension crash constantly

### ISSUE THREAD

**Issue by KarlFrederik** [Ulauncher/Ulauncher#761]
### Steps to reproduce
1. Added my Extension via the GitHub link
-> Crash

### Current behavior
The extension list constantly Crashes. 

### Environment
**Ulauncher version**: v5.11.0
**Linux distro**: Ubuntu 21.04
**Desktop environment**: Gnome

### Logs
Message: Expecting ',' delimiter: line 16 column 7 (char 338)
Error Name: UnhandledError
Type: JSONDecodeError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 426, in prefs_extension_get_all
    return self._get_all_extensions()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 485, in _get_all_extensions
    prefs = ExtensionPreferences.create_instance(ext_id)  # type: ExtensionPreferences
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionPreferences.py", line 35, in create_instance
    return cls(ext_id, ExtensionManifest.open(ext_id))
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 52, in open
    return cls(extension_id, read_manifest(extension_id, extensions_dir), extensions_dir)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 132, in read_manifest
    return load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 16 column 7 (char 338)

```

**Comment by friday** [comment]
My guess is that your configs got messed up. In particular `~/.config/ulauncher/extensions.json`, but possibly other files in ~/.config/ulauncher/

You could move or delete ~/.config/ulauncher/ and try to set it up again from scratch and hopefully this will fix the issue.

**Comment by KarlFrederik** [comment]
I uninstalled Ulauncher and deleted /.config/ulauncher/ and reinstalled it, and it still doesn't work.

**Comment by friday** [comment]
Is it happening for a specific extension? I looked closer and see it's crashing with the read_manifest function, so maybe the manifest is invalid json?

**Comment by friday** [comment]
I think I found it. This line has no comma at the end: https://github.com/KarlFrederik/ulauncher-speedtest/blob/master/manifest.json#L15

**Comment by KarlFrederik** [comment]
Thank you very much for bringing this to my attention. It works now.
