### ISSUE TITLE
Can't add addons

### ISSUE THREAD

**Issue by byIlsa** [Ulauncher/Ulauncher#763]
### Steps to reproduce
1. Click add extension
2. Enter GitHub link
3. Hit save (after making modifications)

### Current behavior
Crash

Message: 'com.github.tchar.ulauncher-albert-calculate-anything'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.tchar.ulauncher-albert-calculate-anything'

```

Message: 'com.github.msaistaken.ulauncher-translator'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.msaistaken.ulauncher-translator'

```

### Expected behavior

Add extensions and make adjustments.

### Environment
**Ulauncher version**:
v5.11.0
**Linux distro**:
OpenSuse Tumbleweed
**Desktop environment**:
Gnome (Wayland)

### Logs
https://gist.github.com/byIlsa/c3c0d4aff05cc7bba33f706993903a88

**Comment by ahoodatheguy** [comment]
Uninstall GTK4

**Comment by byIlsa** [comment]
For anyone else dealing with this: no need to uninstall GTK4.

Just  ```pip3 install pytz --user``` solved it for me.

**Comment by friday** [comment]
> Uninstall GTK4

While that might work to solve extension compatibility issues in general this is not something Ulauncher users should have to do. Next Ulauncher release will fix this issue.

The issue described here however looks very much like a dependency missing from the extension. Check out the readme of the extension page, for example:
https://github.com/tchar/ulauncher-albert-calculate-anything#install-for-ulauncher

**Comment by byIlsa** [comment]
Thanks for your response. 

And you are right. 

Pip3 installing two other packages made it work. 

There are a lot of other things depending on gtk in my installation, so wasn't going to do that anyways 😃
> > Uninstall GTK4
> 
> 
> 
> While that might work to solve extension compatibility issues in general this is not something Ulauncher users should have to do. Next Ulauncher release will fix this issue.
> 
> 
> 
> The issue described here however looks very much like a dependency missing from the extension. Check out the readme of the extension page, for example:
> 
> https://github.com/tchar/ulauncher-albert-calculate-anything#install-for-ulauncher

**Comment by troycurtisjr** [comment]
Linking to common issue #767 for traceability.
