### ISSUE TITLE
I try saving then this error occurs

### ISSUE THREAD

**Issue by ThatOneOcto** [Ulauncher/Ulauncher#838]
Message: 'com.github.tchar.ulauncher-albert-calculate-anything'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 202, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 456, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.tchar.ulauncher-albert-calculate-anything'

```

**Comment by friday** [comment]
Please create a new issue following the issue template. Without the information from the template we can't help.
