### ISSUE TITLE
System management direct fail save

### ISSUE THREAD

**Issue by pbrilius** [Ulauncher/Ulauncher#848]
Message: 'com.github.episode6.ulauncher-system-management-direct'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 202, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 456, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.episode6.ulauncher-system-management-direct'

```

**Comment by friday** [comment]
This is strange. This extension has no dependencies.

There's a bug in Ulauncher for sure, but you can probably just relaunch or restart ulauncher after installing the extension to get past this.

**Comment by friday** [comment]
This issue as described in the trace was fixed by 00c9ae792 (5.14.1), but most likely that issue covered for the real issue which I fixed just now in 88365ae

Should be release very soon (today I think) in v5.16.0. V6 already fixed it before that.
