### ISSUE TITLE
Second start after any extension installed and running leads to ulauncher.api.server.ExtensionServer.ServerIsNotRunningError

### ISSUE THREAD

**Issue by oktayacikalin** [Ulauncher/Ulauncher#958]
### Environment

elementary OS 6.1

### Bug description

1. Install Ulauncher 5.14.3-0ubuntu1ppa1~focal via your ppa
2. Start Ulauncher
3. Install any extension via the pref dialog
4. Test it
5. Exit Ulauncher via the indicator menu item
6. Start Ulauncher
7. Every installed extension triggers an ulauncher.api.server.ExtensionServer.ServerIsNotRunningError

### Log output

```shell
~$ ulauncher -v
2022-01-18 14:54:48,152 | INFO | ulauncher: main() | Ulauncher version 5.14.3
2022-01-18 14:54:48,153 | INFO | ulauncher: main() | Extension API version 2.0.0
2022-01-18 14:54:48,153 | INFO | ulauncher: main() | GTK+ 3.24.20
2022-01-18 14:54:48,154 | INFO | ulauncher: main() | Is Wayland: False
2022-01-18 14:54:48,154 | INFO | ulauncher: main() | Wayland compatibility: off
2022-01-18 14:54:48,283 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-01-18 14:54:48,289 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2022-01-18 14:54:48,289 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-01-18 14:54:48,289 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-01-18 14:54:48,292 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-01-18 14:54:48,294 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-01-18 14:54:48,294 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-01-18 14:54:48,294 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2022-01-18 14:54:48,294 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-01-18 14:54:48,294 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2022-01-18 14:54:48,298 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-01-18 14:54:48,298 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1600, H: 900
2022-01-18 14:54:48,343 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-01-18 14:54:48,347 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionRunner.py", line 83, in _run_process
    env['ULAUNCHER_WS_API'] = self.extension_server.generate_ws_url(extension_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 32, in generate_ws_url
    raise ServerIsNotRunningError()
ulauncher.api.server.ExtensionServer.ServerIsNotRunningError
2022-01-18 14:54:48,450 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 157 apps in cache
2022-01-18 14:54:48,524 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/sessioninstaller.desktop": constructor returned NULL
2022-01-18 14:54:48,577 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 157 apps in the system
2022-01-18 14:54:48,577 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.23 seconds
2022-01-18 14:54:48,605 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2022-01-18 14:54:48,613 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2022-01-18 14:54:50,819 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2022-01-18 14:54:54,396 | INFO | ulauncher.utils.image_loader: get_app_icon_pixbuf() | Could not load icon for lutris_cave-storys-secret-santa. E: gtk-icon-theme-error-quark: Icon 'lutris_cave-storys-secret-santa' not present in theme elementary (0)
2022-01-18 14:54:55,038 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results
2022-01-18 14:54:55,061 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results
2022-01-18 14:54:55,749 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results

(ulauncher:272611): Gtk-CRITICAL **: 14:55:03.123: gtk_main_quit: assertion 'main_loops != NULL' failed
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
Never seen this before. It's a GTK library error, judging by the output. It's also all code we completely rewritten for v6, so it would be a waste of time for us to try to fix it in the v5 branch.

See #869 and https://github.com/Ulauncher/Ulauncher/milestone/7 for info on the new major release. Unfortunately there's still a lot left to do.

**Comment by friday** [comment]
Fixed it v6 by rewriting the extension communication and it should be fixed in v6 now too, ^ (v5.16.0 should be released soon )
