### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sahuvivek2000** [Ulauncher/Ulauncher#976]
### Environment

linux

### Bug description

bug

### Log output

```shell
Message: Expecting value: line 1 column 1 (char 0)
Error Name: UnhandledError
Type: JSONDecodeError

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 415, in prefs_extension_get_all
    return self._get_all_extensions()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 474, in _get_all_extensions
    prefs = ExtensionPreferences.create_instance(ext_id)  # type: ExtensionPreferences
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionPreferences.py", line 35, in create_instance
    return cls(ext_id, ExtensionManifest.open(ext_id))
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 52, in open
    return cls(extension_id, read_manifest(extension_id, extensions_dir), extensions_dir)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionManifest.py", line 132, in read_manifest
    return load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
```


### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by troycurtisjr** [comment]
Can you describe what you were doing when you saw this? This looks like it is trying to load an extension which has a missing manifest.
