### ISSUE TITLE
Installing the Asana extension doesn't work

### ISSUE THREAD

**Issue by skorokithakis** [Ulauncher/Ulauncher#994]
### Environment

Ubuntu 21.10

### Bug description

Trying to add https://github.com/cacciaresi/ulauncher-asana/ produces a 422 error.

### Log output

```shell
Message: HTTP Error 422: Unprocessable Entity
Error Name: UnhandledError
Type: HTTPError

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 202, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 445, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
    commit = gh_ext.find_compatible_version()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 80, in find_compatible_version
    return self.get_commit(sha_or_branch)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 89, in get_commit
    resp = json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

```
```


### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
You checked "This issue applies to the Ulauncher application, not a specific extension", but it's clearly an issue with a specific extension. You should file the bug with the extension idssue page: https://github.com/cacciaresi/ulauncher-asana/issues so @cacciaresi can fix it.

See https://github.com/Ulauncher/Ulauncher/issues/738#issuecomment-897250015
